// 英语要求数据（English language requirements）
// 结构：ENG_RULES[school] = 校级口径（IELTS/TOEFL/GCSE/IGCSE-ESL/IB/GCE + note + url）
//      ENG_PROG[school]  = 逐专业记录（仅帝国、UCL、KCL、曼大、爱丁堡、华威 6 校有；其余 11 校为全校统一）
// 数据核对：2026-09-10；来源：各校官网课程页 / 官方总表（详见 ENGLISH-req-feasibility-17uni.md）

const ENG_RULES = {
 "imperial": {
  "zh": "帝国理工",
  "scope": "mixed",
  "url": "https://www.imperial.ac.uk/study/apply/english-language/",
  "note": "全校只有 Standard / Higher 两档分数，由各课程页单独声明，不按院系；学校资格（GCSE/IGCSE/IB/A-level）两档同分，差异只在考试类。",
  "gcse": "GCSE English Language 6（Home 学生 5；医学 6）",
  "igcseESL": "只认 IGCSE First Language B/6；ESL 不接受",
  "ibEnglish": "IB English A 4；English B HL 5 / SL 6",
  "gceEnglish": "GCE AS/A-Level English Language C（两档同分）",
  "eslFlag": "no",
  "igcseTypeNote": {
   "efl": "",
   "esl": "不接受"
  }
 },
 "ucl": {
  "zh": "UCL",
  "scope": "mixed",
  "url": "https://www.ucl.ac.uk/prospective-students/undergraduate/how-apply/english-language-requirements/",
  "note": "共 Level 1–5 五档，每门专业页标 English language level for this programme is: Level X；同方向内会跳档，必须逐专业查。",
  "gcse": "随 Level 变化（见各行）",
  "igcseESL": "EFL 可覆盖全部 Level；ESL 最高到 Level 2（个别考局到 L3），L3–L5 明确 Not acceptable",
  "ibEnglish": "随 Level 变化（L1/L2 A 5；L3 A 6；L4 A HL6 或 SL7；L5 A HL7、B 不接受）",
  "gceEnglish": "官网认可清单未列 A-Level English",
  "eslFlag": "cond",
  "igcseTypeNote": {
   "efl": "",
   "esl": ""
  }
 },
 "kcl": {
  "zh": "KCL",
  "scope": "mixed",
  "url": "https://www.kcl.ac.uk/study/undergraduate/how-to-apply/english-language-requirements",
  "note": "本科用 Band A / B / D（C 仅研究生、E 无人用）；Band 由「学院归属 + 具名课单」决定，页面本身不写 Band。",
  "gcse": "GCSE English Language B/6（三档相同）",
  "igcseESL": "接受 ESL 但需 A/7；First Language 仅需 B/6；EFL 不接受",
  "ibEnglish": "IB English A HL4/SL5；English B HL5/SL7（三档相同）",
  "gceEnglish": "GCE AS/A-Level English Language C（三档相同）",
  "eslFlag": "yes",
  "igcseTypeNote": {
   "efl": "",
   "esl": "A/7"
  }
 },
 "manchester": {
  "zh": "曼大",
  "scope": "mixed",
  "url": "https://www.manchester.ac.uk/study/international/admissions/language-requirements/",
  "note": "官网总页只给典型档，各专业分数在 2027 课程页各自写明（6.0–7.0 不等）。",
  "gcse": "随专业（4/C 或 B/6，见各行）",
  "igcseESL": "有条件接受 ESL：仅限 CAIE / Oxford AQA / Pearson Edexcel 三家；6.5 档课程需 Grade 8、6.0 档需 Grade 7、7.0 档课程不接受",
  "ibEnglish": "MYP / IB English 按官网 GCSE 换算表对应",
  "gceEnglish": "官网未列 A-Level English",
  "eslFlag": "cond",
  "igcseTypeNote": {
   "efl": "",
   "esl": ""
  }
 },
 "edinburgh": {
  "zh": "爱丁堡",
  "scope": "mixed",
  "url": "https://study.ed.ac.uk/undergraduate/entry-requirements/english-language",
  "note": "总页声明 requirements vary between degrees；逐课程 /entry-requirements 页各写；实测两档（6.5 与商科 7.0）。",
  "gcse": "GCSE English at C/4",
  "igcseESL": "第一或第二语言均接受；不接受 IGCSE/CIE English (as an Additional Language) 与 IGCSE English Literature",
  "ibEnglish": "IB English A/B：SL 5 或 HL 4（ab initio 不接受）",
  "gceEnglish": "AS/A-Level English（Language / Lang&Lit / Literature）C",
  "eslFlag": "yes",
  "igcseTypeNote": {
   "efl": "",
   "esl": ""
  }
 },
 "warwick": {
  "zh": "华威",
  "scope": "mixed",
  "url": "https://warwick.ac.uk/study/undergraduate/applying/english-language-requirements/",
  "note": "Band A/B/C 三档；每门课程页写 This course requires: Band X；Band C 四门另有 GCSE 加码。",
  "gcse": "GCSE English Language：Band A/B 需 4/C；Band C 需 6/B",
  "igcseESL": "ESL 不接受；First Language：A/B 档 C、C 档 B",
  "ibEnglish": "IB English A HL4/SL4（C 档 HL5/SL5）；English B HL4/SL5（C 档 HL5/SL6）",
  "gceEnglish": "GCE A-Level English C（C 档 B）",
  "eslFlag": "no",
  "igcseTypeNote": {
   "efl": "",
   "esl": "不接受"
  }
 },
 "oxford": {
  "zh": "牛津",
  "scope": "school",
  "url": "https://www.ox.ac.uk/admissions/undergraduate/applying/for-international-students/english-language-requirements-visas",
  "ielts": "7.5（各项不低于 7.0）",
  "toeflOld": "110（听22 读24 说25 写24）",
  "toeflNew": "2026-01-21 起的新版考试暂不受理",
  "gcse": "GCSE English Language B/6 + 口语 Merit",
  "igcseESL": "不接受（只认 First Language：B/6 + 口语达标）",
  "ibEnglish": "English B HL 7",
  "gceEnglish": "官网未列 A-Level English",
  "note": "全校统一一档，不分专业；条件须在 offer 当年 7 月 31 日前达到，不接受拼分。",
  "gcseNote": "",
  "eslFlag": "no",
  "igcseTypeNote": {
   "efl": "",
   "esl": "不接受"
  }
 },
 "cambridge": {
  "zh": "剑桥",
  "scope": "school",
  "url": "https://www.undergraduate.study.cam.ac.uk/apply/before/entry-requirements#english-language-requirements",
  "ielts": "7.5（各项不低于 7.0）；面试阶段建议 6.5（各项 6.0）",
  "toeflOld": "官网现行页已不列 TOEFL",
  "toeflNew": "—",
  "gcse": "官网未列 GCSE/IGCSE English",
  "igcseESL": "官网未列",
  "ibEnglish": "官网未列",
  "gceEnglish": "官网未列",
  "note": "全校统一；最终语言条件由发出 offer 的学院个案决定。",
  "gcseNote": "",
  "eslFlag": "unknown",
  "igcseTypeNote": {
   "efl": "官网未列",
   "esl": "官网未列"
  }
 },
 "lse": {
  "zh": "LSE",
  "scope": "school",
  "url": "https://www.lse.ac.uk/study-at-lse/Undergraduate/Prospective-Students/How-to-Apply/English-language-requirements",
  "ielts": "7.0（各项 7.0）",
  "toeflOld": "100（写27 读25 听24 说24）",
  "toeflNew": "5.5（各项 5）",
  "gcse": "GCSE English Language B/6",
  "igcseESL": "不接受（只认 IGCSE First Language）",
  "ibEnglish": "English A：HL 任意 / SL ≥6；English B：HL 7",
  "gceEnglish": "官网未列 A-Level English",
  "note": "本科全校统一（Standard/Higher 分档仅适用于研究生）。",
  "gcseNote": "",
  "eslFlag": "no",
  "igcseTypeNote": {
   "efl": "",
   "esl": "不接受"
  }
 },
 "hku": {
  "zh": "港大",
  "scope": "school",
  "url": "https://admissions.hku.hk/apply/international-qualifications/english-language-requirement",
  "ielts": "6.5（同一次考试、两年内）",
  "toeflOld": "93",
  "toeflNew": "—",
  "gcse": "GCSE/GCEO English Language C（9-1 制 4）",
  "igcseESL": "接受：Second Language 需 B（5）；First Language 只需 C（4）",
  "ibEnglish": "English A（HL/SL）4；English B：HL 4 / SL 5",
  "gceEnglish": "GCE AS/AL English Language 或 Literature C",
  "note": "全校统一（官方 API 逐个专业比对，55 个专业取值完全一致）。",
  "gcseNote": "",
  "eslFlag": "yes",
  "igcseTypeNote": {
   "efl": "",
   "esl": "B（5）"
  }
 },
 "cuhk": {
  "zh": "港中文",
  "scope": "school",
  "url": "https://admission.cuhk.edu.hk/application/non-jupas/language-requirements/",
  "ielts": "6.0",
  "toeflOld": "80",
  "toeflNew": "4.5（2026-01-21 起）",
  "gcse": "GCSE/IGCSE/GCE-OL Grade C / 4",
  "igcseESL": "官网未区分 ESL/EFL（只写 GCSE/IGCSE）",
  "ibEnglish": "IB English 4（官网未区分 A/B）",
  "gceEnglish": "GCE-AL/AS English E",
  "note": "全校统一；例外：环球商业 GBS 需 IELTS 7.0 / TOEFL 100。",
  "gcseNote": "",
  "eslFlag": "unknown",
  "igcseTypeNote": {
   "efl": "官网未区分",
   "esl": "官网未区分"
  }
 },
 "hkust": {
  "zh": "港科大",
  "scope": "school",
  "url": "https://join.hkust.edu.hk/admissions/international-qualifications",
  "ielts": "6.0",
  "toeflOld": "80（一次考试）",
  "toeflNew": "4.5（2026-01-21 起）",
  "gcse": "GCSE/GCE O-Level English Language 或 Literature 4/C；GCE AS/A English E",
  "igcseESL": "接受：Second Language 需 5/B（First Language 4/C）",
  "ibEnglish": "English A（HL/SL）4；English B：HL 4 / SL 5",
  "gceEnglish": "GCE AS/A-Level English E",
  "note": "全校统一；专业维度不含英语要求（官方接口确认）。",
  "gcseNote": "",
  "eslFlag": "yes",
  "igcseTypeNote": {
   "efl": "",
   "esl": "5/B"
  }
 },
 "cityu": {
  "zh": "城大",
  "scope": "school",
  "url": "https://www.cityu.edu.hk/admo/admissions/non-jupas-year-1-admission",
  "ielts": "6.5",
  "toeflOld": "79（不收 MyBest）",
  "toeflNew": "—",
  "gcse": "GCSE/GCE O-Level English Language 或 Literature C/4",
  "igcseESL": "接受：Second Language 需 B/5（First Language C/4）",
  "ibEnglish": "English B SL 5",
  "gceEnglish": "GCE AL/IAL 或 AS/IAS English E",
  "note": "全校统一；例外：BBA Business Economics 需 IELTS 7.0（法律 LLB、兽医学 BVM 等未收录专业亦有更高要求）。",
  "gcseNote": "",
  "eslFlag": "yes",
  "igcseTypeNote": {
   "efl": "",
   "esl": "B/5"
  }
 },
 "polyu": {
  "zh": "理大",
  "scope": "school",
  "url": "https://www.polyu.edu.hk/study/ug/admissions/international-other-qualifications/international-other-qualifications-english",
  "ielts": "6.0（一次考试）",
  "toeflOld": "80",
  "toeflNew": "—",
  "gcse": "GCSE/IGCSE/GCE O-Level English C/4；GCE AS/A-Level English E",
  "igcseESL": "官网未列 ESL/EFL（只写 English / English Language / English Literature）",
  "ibEnglish": "IB English 或 English Literature（HL/SL）4",
  "gceEnglish": "GCE AS/A-Level English E",
  "note": "全校统一；抽查 10 个专业（含护理/物理治疗/放射/医疗化验）均无更高门槛。",
  "gcseNote": "",
  "eslFlag": "unknown",
  "igcseTypeNote": {
   "efl": "官网未区分",
   "esl": "官网未区分"
  }
 },
 "hkbu": {
  "zh": "浸会",
  "scope": "school",
  "url": "https://admissions.hkbu.edu.hk/admissions/international-qualifications.html",
  "ielts": "6.0",
  "toeflOld": "79（不收 MyBest）",
  "toeflNew": "—",
  "gcse": "GCSE/GCE O-Level English / English Language / English Literature C/4",
  "igcseESL": "接受：Second Language 需 B/5；First Language C/4",
  "ibEnglish": "English A（HL/SL）4；English B：HL 4 / SL 5",
  "gceEnglish": "GCE AS/A-Level English E",
  "note": "全校统一；中医/中药/中文类专业另需中文资历（非英语要求）。",
  "gcseNote": "",
  "eslFlag": "yes",
  "igcseTypeNote": {
   "efl": "",
   "esl": "B/5"
  }
 },
 "eduhk": {
  "zh": "教育",
  "scope": "school",
  "url": "https://www.apply.eduhk.hk/ug/nonlocal",
  "ielts": "6.0",
  "toeflOld": "80（新制 4）",
  "toeflNew": "4（2026-01-21 起）",
  "gcse": "GCSE/IGCSE/GCE O-Level English C/4",
  "igcseESL": "官网未区分 ESL/EFL",
  "ibEnglish": "English A（HL/SL）4；English B：HL 4 / SL 5",
  "gceEnglish": "GCE AS/A-Level English E",
  "note": "全校统一；英文教育双学位（JS8004）有“高英语水平”定性要求，但官网未设更高分数。",
  "gcseNote": "",
  "eslFlag": "unknown",
  "igcseTypeNote": {
   "efl": "官网未区分",
   "esl": "官网未区分"
  }
 },
 "lingnan": {
  "zh": "岭南",
  "scope": "school",
  "url": "https://www.ln.edu.hk/admissions/ug/apply-now/overseas-and-mainland-applicants-holding-international-qualifications",
  "ielts": "6.0",
  "toeflOld": "79",
  "toeflNew": "—",
  "gcse": "GCSE/IGCSE English / English Language / English Literature C/4",
  "igcseESL": "官网未列 ESL/EFL",
  "ibEnglish": "English A（HL/SL）4；English B：HL 4 / SL 5",
  "gceEnglish": "GCE AS/A-Level English E",
  "note": "全校统一（国际资格版与本地 non-JUPAS 版同一张表）。",
  "gcseNote": "",
  "eslFlag": "unknown",
  "igcseTypeNote": {
   "efl": "官网未列",
   "esl": "官网未列"
  }
 }
};

const ENG_PROG = {
 "imperial": [
  {
   "en": "Medical Biosciences",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Biochemistry",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Biological Sciences",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Chemistry",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Physics",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Aeronautical Engineering",
   "band": "Standard",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.5）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Mechanical Engineering",
   "band": "Standard",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.5）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Electrical and Electronic Engineering",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Civil Engineering",
   "band": "Standard",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.5）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Chemical Engineering",
   "band": "Standard",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.5）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Design Engineering",
   "band": "Standard",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.5）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Biomedical Engineering",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Economics, Finance and Data Science",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Computing (MEng)",
   "band": "Standard",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.5）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Computing (BEng)",
   "band": "Standard",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.5）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Mathematics",
   "band": "Higher",
   "ielts": "7.0（各项≥6.5）",
   "toeflOld": "100（各项≥22）",
   "toeflNew": "5.0（各项≥5.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  }
 ],
 "ucl": [
  {
   "en": "Biomedical Sciences",
   "band": "Level 4",
   "ielts": "7.5（各项7.0）",
   "toeflOld": "109",
   "toeflNew": "5.5（各项5.0）",
   "gcse": "GCSE English Language 6 + Distinction",
   "eslGrade": "ESL 不接受",
   "ibEnglish": "IB English A：HL6 或 SL7；English B HL7",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Biochemistry",
   "band": "Level 4",
   "ielts": "7.5（各项7.0）",
   "toeflOld": "109",
   "toeflNew": "5.5（各项5.0）",
   "gcse": "GCSE English Language 6 + Distinction",
   "eslGrade": "ESL 不接受",
   "ibEnglish": "IB English A：HL6 或 SL7；English B HL7",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Chemistry",
   "band": "Level 2",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "96",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL6 或 SL7",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Physics",
   "band": "Level 1",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5（各项4.0）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL5 或 SL6",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Mechanical Engineering",
   "band": "Level 1",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5（各项4.0）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL5 或 SL6",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Civil Engineering",
   "band": "Level 1",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5（各项4.0）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL5 或 SL6",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Electronic and Electrical Engineering",
   "band": "Level 2",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "96",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL6 或 SL7",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Economics",
   "band": "Level 2",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "96",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL6 或 SL7",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Management Science",
   "band": "Level 4",
   "ielts": "7.5（各项7.0）",
   "toeflOld": "109",
   "toeflNew": "5.5（各项5.0）",
   "gcse": "GCSE English Language 6 + Distinction",
   "eslGrade": "ESL 不接受",
   "ibEnglish": "IB English A：HL6 或 SL7；English B HL7",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Computer Science (BSc)",
   "band": "Level 1",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5（各项4.0）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL5 或 SL6",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Computer Science (MEng)",
   "band": "Level 1",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5（各项4.0）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL5 或 SL6",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Data Science",
   "band": "Level 2",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "96",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL6 或 SL7",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Statistics",
   "band": "Level 2",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "96",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL6 或 SL7",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Statistics with Economics and Finance",
   "band": "Level 2",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "96",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE English Language 4 + Merit（口语）",
   "eslGrade": "ESL 可（最高到 L2）",
   "ibEnglish": "IB English A 5；English B HL6 或 SL7",
   "extra": "",
   "eslFlag": "yes"
  }
 ],
 "kcl": [
  {
   "en": "Biomedical Science",
   "band": "Band D",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Biochemistry",
   "band": "Band D",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Pharmacy",
   "band": "Band B",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Physics",
   "band": "Band D",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "General Engineering",
   "band": "Band B",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Electronic Engineering",
   "band": "Band B",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Biomedical Engineering",
   "band": "Band D",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Economics",
   "band": "Band B",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Economics and Management",
   "band": "Band B",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Business Management",
   "band": "Band B",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Computer Science",
   "band": "Band D",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Artificial Intelligence",
   "band": "Band D",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Mathematics with Statistics",
   "band": "Band D",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Mathematics",
   "band": "Band D",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  }
 ],
 "manchester": [
  {
   "en": "Biochemistry",
   "band": "",
   "ielts": "6.5（各项≥6.5）",
   "toeflOld": "—",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language 4/C",
   "eslGrade": "未列具体等级（通用提示）",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "unknown"
  },
  {
   "en": "Physics",
   "band": "",
   "ielts": "6.0（各项≥5.5）",
   "toeflOld": "—",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language 4/C",
   "eslGrade": "未列；另需 IGCSE Oral Exam 1/2 级",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "unknown"
  },
  {
   "en": "Mechanical Engineering",
   "band": "",
   "ielts": "6.5（各项≥6.5）",
   "toeflOld": "90（各项≥22）",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE/IGCSE English Language 4/C",
   "eslGrade": "接受：Grade 8；仅限 CAIE / Oxford AQA / Pearson Edexcel",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  },
  {
   "en": "Electrical and Electronic Engineering",
   "band": "",
   "ielts": "7.0（写作7.0、其余6.5）",
   "toeflOld": "100（写作25、其余22）",
   "toeflNew": "5.0（写作5.0、其余4.5）",
   "gcse": "GCSE/IGCSE English Language B/6（English Literature 不可替代）",
   "eslGrade": "不接受",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Aerospace Engineering",
   "band": "",
   "ielts": "6.5（各项≥6.5）",
   "toeflOld": "90（各项≥22）",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE/IGCSE English Language 4/C",
   "eslGrade": "接受：Grade 8；仅限 CAIE / Oxford AQA / Pearson Edexcel",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  },
  {
   "en": "Chemical Engineering",
   "band": "",
   "ielts": "6.5（各项≥6.5）",
   "toeflOld": "90（各项≥22）",
   "toeflNew": "4.5（各项4.5）",
   "gcse": "GCSE/IGCSE English Language 4/C",
   "eslGrade": "接受：Grade 8；仅限 CAIE / Oxford AQA / Pearson Edexcel",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  },
  {
   "en": "Economics",
   "band": "",
   "ielts": "6.5（各项≥6）",
   "toeflOld": "90（各项≥20）",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language C",
   "eslGrade": "接受：Grade B",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  },
  {
   "en": "Accounting and Finance (BAEcon)",
   "band": "",
   "ielts": "6.5（各项≥6）",
   "toeflOld": "90（各项≥20）",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language C",
   "eslGrade": "接受：Grade B",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  },
  {
   "en": "Accounting (BSc)",
   "band": "",
   "ielts": "6.5（各项≥6）",
   "toeflOld": "—",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language B/6",
   "eslGrade": "未列具体等级",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "unknown"
  },
  {
   "en": "Management",
   "band": "",
   "ielts": "6.5（各项≥6）",
   "toeflOld": "—",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language B/6",
   "eslGrade": "未列具体等级",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "unknown"
  },
  {
   "en": "Computer Science",
   "band": "",
   "ielts": "6.5（各项≥6.5）",
   "toeflOld": "90（各项≥22）",
   "toeflNew": "4.5（各项≥4.5）",
   "gcse": "GCSE/IGCSE English Language C/4（English Literature 不可替代）",
   "eslGrade": "接受：Grade 8；仅限 CAIE / Oxford AQA / Pearson Edexcel",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  },
  {
   "en": "Data Science and Economics (BAEcon)",
   "band": "",
   "ielts": "6.5（各项≥6）",
   "toeflOld": "90（各项≥20）",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language C",
   "eslGrade": "接受：Grade B",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  },
  {
   "en": "Mathematics and Statistics",
   "band": "",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "90（各项≥20）",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language C/4",
   "eslGrade": "接受：Grade 8；仅限 CAIE / Oxford AQA / Pearson Edexcel",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  },
  {
   "en": "Mathematics",
   "band": "",
   "ielts": "6.5（各项≥6.0）",
   "toeflOld": "90（各项≥20）",
   "toeflNew": "未列",
   "gcse": "GCSE/IGCSE English Language C/4",
   "eslGrade": "接受：Grade 8；仅限 CAIE / Oxford AQA / Pearson Edexcel",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "cond"
  }
 ],
 "edinburgh": [
  {
   "en": "Biological Sciences (Biochemistry)",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Chemistry",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Physics",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Electronics and Electrical Engineering",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Mechanical Engineering",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Chemical Engineering",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Civil Engineering",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Economics",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Accounting and Finance",
   "band": "",
   "ielts": "7.0（各项≥6.0）",
   "toeflOld": "100（各项≥20）",
   "toeflNew": "5.0（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Business Management",
   "band": "",
   "ielts": "7.0（各项≥6.0）",
   "toeflOld": "100（各项≥20）",
   "toeflNew": "5.0（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Computer Science",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  },
  {
   "en": "Mathematics and Statistics",
   "band": "",
   "ielts": "6.5（各项≥5.5）",
   "toeflOld": "92（各项≥20）",
   "toeflNew": "4.5（各项≥4.0）",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "yes"
  }
 ],
 "warwick": [
  {
   "en": "Biomedical Sciences",
   "band": "Band A",
   "ielts": "6.0（各项5.5）",
   "toeflOld": "87",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Biochemistry",
   "band": "Band A",
   "ielts": "6.0（各项5.5）",
   "toeflOld": "87",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Chemistry",
   "band": "Band A",
   "ielts": "6.0（各项5.5）",
   "toeflOld": "87",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Physics",
   "band": "Band A",
   "ielts": "6.0（各项5.5）",
   "toeflOld": "87",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Engineering",
   "band": "Band A",
   "ielts": "6.0（各项5.5）",
   "toeflOld": "87",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Economics",
   "band": "Band C",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "另需 GCSE English Language 6/B",
   "eslFlag": "no"
  },
  {
   "en": "Accounting and Finance",
   "band": "Band C",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "另需 GCSE English Language 6/B（或 English Literature 6/B + Language 4/C）",
   "eslFlag": "no"
  },
  {
   "en": "Business and Management",
   "band": "Band C",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "另需 GCSE English Language 6/B + GCSE Maths 7/A",
   "eslFlag": "no"
  },
  {
   "en": "International Business and Management",
   "band": "Band C",
   "ielts": "7.0（各项6.5）",
   "toeflOld": "100",
   "toeflNew": "5.0",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "另需 GCSE English Language 6/B + GCSE Maths 7/A",
   "eslFlag": "no"
  },
  {
   "en": "Computer Science",
   "band": "Band A",
   "ielts": "6.0（各项5.5）",
   "toeflOld": "87",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Data Science",
   "band": "Band A",
   "ielts": "6.0（各项5.5）",
   "toeflOld": "87",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "MORSE",
   "band": "Band B",
   "ielts": "6.5（各项6.0）",
   "toeflOld": "92",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  },
  {
   "en": "Mathematics",
   "band": "Band A",
   "ielts": "6.0（各项5.5）",
   "toeflOld": "87",
   "toeflNew": "4.5",
   "gcse": "",
   "eslGrade": "",
   "ibEnglish": "",
   "extra": "",
   "eslFlag": "no"
  }
 ],
 "cuhk": [
  {
   "en": "Global Business Studies",
   "tag": "例外",
   "band": "",
   "ielts": "7.0",
   "toeflOld": "100",
   "toeflNew": "—",
   "gcse": "",
   "igcseESL": "",
   "ibEnglish": "",
   "extra": "环球商业 GBS 另订更高英语要求（官网 programme list 备注）",
   "eslFlag": "unknown"
  }
 ],
 "cityu": [
  {
   "en": "BBA Business Economics",
   "tag": "例外",
   "band": "",
   "ielts": "7.0",
   "toeflOld": "",
   "toeflNew": "—",
   "gcse": "",
   "igcseESL": "",
   "ibEnglish": "",
   "extra": "商业经济另订更高英语要求（官网）",
   "eslFlag": "yes"
  }
 ]
};
