// 英国九校本科录取要求速查 —— 数据（2026-09 抓取核对，面向 2027 年 9 月入学申请季）
// 方向编码：bio=生化医药化学 / physics=物理 / eng=工程 / econ=经济管理金融会计 / cs=计算机数据AI / stats=统计数学精算 / edu=教育 / social=社科传媒人文
// 成绩口径见"术语与口径说明"：典型（典型录取水平）/ 最低 / 区间；剑桥为各学院最低 offer 水平

const SCHOOLS = [
  { key: 'oxford',    zh: '牛津',   en: 'University of Oxford',  group: 'G5·牛剑', mark: '牛', color: '#7c0f28', checked: '2026-09' },
  { key: 'cambridge', zh: '剑桥',   en: 'University of Cambridge', group: 'G5·牛剑', mark: '剑', color: '#0f4c81', checked: '2026-09' },
  { key: 'imperial',  zh: '帝国理工', en: 'Imperial College London', group: 'G5', mark: '帝', color: '#162d5c', checked: '2026-09' },
  { key: 'lse',       zh: 'LSE',    en: 'London School of Economics', group: 'G5', mark: 'LSE', color: '#a61c5b', checked: '2026-09' },
  { key: 'ucl',       zh: 'UCL',    en: 'University College London', group: 'G5', mark: 'UCL', color: '#511c5c', checked: '2026-09' },
  { key: 'kcl',       zh: 'KCL',    en: "King's College London", group: '王爱曼华', mark: 'KCL', color: '#3a5da8', checked: '2026-09' },
  { key: 'manchester',zh: '曼大',   en: 'University of Manchester', group: '王爱曼华', mark: '曼', color: '#73172d', checked: '2026-09' },
  { key: 'edinburgh', zh: '爱丁堡', en: 'University of Edinburgh', group: '王爱曼华', mark: '爱', color: '#1e2d3d', checked: '2026-09' },
  { key: 'warwick',   zh: '华威',   en: 'University of Warwick',  group: '王爱曼华', mark: '华', color: '#4b1e64', checked: '2026-09' }
];

const DIRS = {
  bio:      { zh: '生物·化学·医药', en: 'Biochem/Chem/Bio/Med', short: '生化医药' },
  physics:  { zh: '物理',           en: 'Physics',               short: '物理' },
  eng:      { zh: '工程',           en: 'Engineering',           short: '工程' },
  econ:     { zh: '经济·管理·金融·会计', en: 'Econ/Management/Finance', short: '经管金融' },
  cs:       { zh: '计算机·数据·AI', en: 'CS/Data/AI',            short: '计算机数据' },
  stats:    { zh: '统计·数学·精算', en: 'Stats/Maths',           short: '统计数学' },
  // 教育 / 人文 / 社科三个方向两个板块都有专业；传媒目前只有香港板块有，某方向在本板块无专业时不显示该筛选项
  edu:      { zh: '教育',           en: 'Education',             short: '教育' },
  arts:     { zh: '人文·语言',      en: 'Arts/Languages',        short: '人文语言' },
  social:   { zh: '社科·法律',      en: 'Social Sciences/Law',   short: '社科法律' },
  media:    { zh: '传媒',           en: 'Communication/Media',   short: '传媒' }
};

// test 取值：''（无笔试）| 'ESAT' | 'TMUA' | 'TARA' | 'LNAT'（法学）| 'STEP'（剑桥数学offer附加）| 'UCAT' | 组合如 'ESAT'+说明写 note
// offer 口径（仅决定表内标签与释义，代码值保持不变）：typical | min | range | college | standard → 显示为 典型 / 最低 / 区间
const PROGRAMS = [

  // ═══════════ 牛津 Oxford（standard：课程页标准要求；均需线上面试） ═══════════

  

  

  

  { school: 'oxford', dirs: ['bio'], zh: '生物化学（分子与细胞生物学）', en: 'Biochemistry (Molecular and Cellular Biology)',
    degree: 'MBiochem · 4 年', alevel: 'A*AA', ib: '39（HL 化学 7 + 另两门相关 6）', test: '',
    alevelNote: '化学必修 + 另一门科学/数学；A* 须在科学/数学科目', offer: 'standard', note: '无笔试；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biochemistry-molecular-and-cellular' },

  { school: 'oxford', dirs: ['bio'], zh: '生物学', en: 'Biology',
    degree: 'BA / MBiol · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 生物 + 科学/数学之一 7）', test: '',
    alevelNote: '生物必修 + 化学/物理/数学之一；A* 须在科学/数学', offer: 'standard', note: '无笔试；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biology' },

  { school: 'oxford', dirs: ['bio'], zh: '生物医学', en: 'Biomedical Sciences',
    degree: 'MBiomedSci / BA · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766）', test: 'ESAT',
    alevelNote: '生物/化学/物理/数学须选两门；不收 Critical Thinking 等', offer: 'standard', note: 'ESAT：Maths 1 + 自选两门；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biomedical-sciences' },

  { school: 'oxford', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'MChem · 4 年', alevel: 'A*A*A', ib: '40（HL 化学 7）', test: '',
    alevelNote: '化学 + 数学必修，两个 A* 均须在科学/数学科目', offer: 'standard', note: '无笔试；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/chemistry' },

  { school: 'oxford', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'MPhys / BA · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766，7 在物理或数学）', test: 'ESAT',
    alevelNote: '数学 + 物理必修；A* 须在数学/物理/高数', offer: 'standard', note: '2027 起 ESAT 取代 PAT（Maths1/2 + Physics）；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/physics' },

  { school: 'oxford', dirs: ['eng'], zh: '工程科学', en: 'Engineering Science',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 776，数学与物理均 7）', test: 'ESAT',
    alevelNote: '数学 + 物理必修，两个 A* 在数学/物理/高数', offer: 'standard', note: 'ESAT（Maths1/2 + Physics）；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/engineering-science' },

  { school: 'oxford', dirs: ['econ'], zh: '经济与管理', en: 'Economics and Management',
    degree: 'BA · 3 年', alevel: 'A*AA', ib: '39（HL 766，HL 数学 6 或 7）', test: 'TARA',
    alevelNote: '数学必修（A* 或 A）', offer: 'standard', note: 'TARA 考 Critical Thinking + Problem Solving 两模块',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/economics-and-management' },

  { school: 'oxford', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BA / MCompSci · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766，7 在 HL 数学）', test: 'TMUA',
    alevelNote: '数学 + 高数 A*A（学校开高数须选）；不开高数则 A*AAa 或 A*AA（数学 A*）', offer: 'standard', note: '2027 起 TMUA 取代 MAT；近年约 96% 录取者修过高数',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/computer-science' },

  { school: 'oxford', dirs: ['stats'], zh: '数学（含数学与统计路线）', en: 'Mathematics / Mathematics and Statistics',
    degree: 'BA / MMath · 3 或 4 年', alevel: 'A*A*A', ib: '39（HL 766，7 在 HL 数学）', test: 'TMUA',
    alevelNote: '数学 + 高数均 A*（同 CS 的不开高数替代路径）', offer: 'standard', note: '申请即联合 Math & Stats，第四学期末分纯数 / 数统路线',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/mathematics' },




// ── 牛津 · 社科 / 法律 / 人文（2027 起社科类笔试改考 TARA；法学 LNAT） ──
  { school: 'oxford', dirs: ['social'], zh: '法学（法理学）', en: 'Law (Jurisprudence)',
    degree: 'BA · 3 或 4 年', alevel: 'AAA', ib: '38（HL 666）', test: 'LNAT',
    alevelNote: '无必修科目；作文类科目有帮助', offer: 'standard',
    note: 'LNAT 考试窗口 9 月 1 日–10 月 15 日；无须提交书面作品；须线上面试（12 月）',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/law-jurisprudence' },

  { school: 'oxford', dirs: ['social'], zh: '哲学、政治学与经济学（PPE）', en: 'Philosophy, Politics and Economics',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '39（HL 766）', test: 'TARA',
    alevelNote: '建议修数学至 A-level（非必须，但多数录取者修数学）', offer: 'standard',
    note: 'TARA 三模块（Critical Thinking + Problem Solving + Writing Task）；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/philosophy-politics-and-economics' },

  { school: 'oxford', dirs: ['social'], zh: '心理学（实验心理学）', en: 'Psychology (Experimental)',
    degree: 'BA · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766）', test: 'TARA',
    alevelNote: '强烈建议修一门科学（含心理学）或数学；建议 GCSE 数学 A/7 以上', offer: 'standard',
    note: 'TARA 三模块；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/psychology-experimental' },

  { school: 'oxford', dirs: ['social'], zh: '人类科学', en: 'Human Sciences',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '38（HL 666）', test: 'TARA',
    alevelNote: '无必修；生物或数学有帮助', offer: 'standard',
    note: '跨生物与社会科学的交叉课程；TARA 三模块；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/human-sciences' },

  { school: 'oxford', dirs: ['social'], zh: '地理学', en: 'Geography',
    degree: 'BA · 3 年', alevel: 'A*AA', ib: '39（HL 766）', test: '',
    alevelNote: '建议修地理', offer: 'standard',
    note: '无笔试；无须提交书面作品；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/geography' },

  { school: 'oxford', dirs: ['social', 'arts'], zh: '心理学、哲学与语言学（PPL）', en: 'Psychology, Philosophy and Linguistics',
    degree: 'BA · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766）', test: 'TARA',
    alevelNote: '建议 GCSE 数学 A/7 以上；心理学方向建议科学/数学，语言学方向建议英语语言、数学、科学或语言',
    offer: 'standard', note: 'TARA 三模块；按 UCAS 代码分心哲 / 心语 / 哲语三条路线；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/psychology-philosophy-and-linguistics' },

  { school: 'oxford', dirs: ['arts'], zh: '历史学', en: 'History',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '38（HL 666）', test: '',
    alevelNote: '强烈建议修历史', offer: 'standard',
    note: '无笔试；须提交一篇 2000 词以内的历史论文；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/history' },

  { school: 'oxford', dirs: ['arts'], zh: '英语语言与文学', en: 'English Language and Literature',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '38（HL 666）', test: '',
    alevelNote: '必修英语文学或英语语言与文学；不接受创意写作资历', offer: 'standard',
    note: '无笔试；须提交一篇英语文学分析文（2000 词以内）；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/english-language-and-literature' },

  { school: 'oxford', dirs: ['arts'], qs: [], zh: '古典学（Literae Humaniores）', en: 'Classics',
    degree: 'BA · 4 年', alevel: 'AAA', ib: '39（HL 666）', test: '',
    alevelNote: '无必修；若修拉丁语/希腊语则须达 A；古典文明、古代史或现代语言有帮助', offer: 'standard',
    note: '无笔试；须提交两份书面作品；拉丁 / 希腊语能力在面试中测试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/classics' },

  { school: 'oxford',
    dirs: ['social'],
    zh: '考古与人类学',
    en: 'Archaeology and Anthropology BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '38（HL 666）',
    alevelNote: '无特定科目要求',
    test: '',
    offer: 'standard',
    note: 'UCAS LV64；无入学笔试，需提交两篇近期在校批改论文；12 月线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/archaeology-and-anthropology' },

  { school: 'oxford',
    dirs: ['arts'],
    zh: '现代语言',
    en: 'Modern Languages',
    degree: 'BA · 4 年',
    alevel: 'AAA',
    ib: '38（HL 666）',
    alevelNote: '通常须有所修语言达 A-level / IB HL（或 CEFR B1）；法语申请者须有法语 A-level；除法语、西班牙语外可从零起点学',
    test: '',
    offer: 'standard',
    note: '需修两门语言，其中一门可零起点；无入学笔试、无需提交书面作品；12 月线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/modern-languages' },

  { school: 'oxford',
    dirs: ['arts'],
    zh: '音乐',
    en: 'Music',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '38（HL 666）',
    alevelNote: '须有 Music A-level / IB HL，或乐理 7 级以上（ABRSM、Trinity 等）',
    test: '',
    offer: 'standard',
    note: '无入学笔试；须提交不超过 5 分钟演奏视频，另交三篇书面作品（两篇约 1500 字论文 + 一篇和声/对位练习），截止 11 月 10 日',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/music' },

  { school: 'oxford',
    dirs: ['arts'],
    zh: '哲学与神学',
    en: 'Philosophy and Theology',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '39（HL 666）',
    alevelNote: '无必修科目；写作类科目有帮助',
    test: '',
    offer: 'standard',
    note: '无入学笔试；须提交一篇不超过 2000 字的近期在校论文（任何科目）；12 月线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/philosophy-and-theology' },

  { school: 'oxford',
    dirs: ['arts'],
    zh: '神学与宗教',
    en: 'Theology and Religion',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '38（HL 666）',
    alevelNote: '无必修科目；写作类科目有帮助',
    test: '',
    offer: 'standard',
    note: '无入学笔试；须提交一篇不超过 2000 字的近期在校论文（任何科目）；12 月线上面试',
    qs: [],
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/theology-and-religion' },

  { school: 'oxford',
    dirs: ['arts'],
    zh: '美术',
    en: 'Fine Art',
    degree: 'BFA · 3 年',
    alevel: 'AAA（或 AAB + Art Foundation）',
    ib: '38（HL 666）',
    alevelNote: '无必修科目；Ruskin 建议修 Art A-level，并强烈建议先完成 post-18 Art Foundation 课程（AAB + Foundation Merit 路径）',
    test: '',
    offer: 'standard',
    note: 'Ruskin 艺术学院三年制工作室制 BFA；无入学笔试；须经 SlideRoom 提交数字作品集，截止 11 月 5 日',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/fine-art' },

  { school: 'oxford',
    dirs: ['arts', 'social'],
    zh: '历史与政治',
    en: 'History and Politics',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '38（HL 666）',
    alevelNote: '强烈建议 History A-level / IB HL；社会学、政治学有帮助',
    test: 'TARA',
    offer: 'standard',
    note: '2027 起入学笔试为 TARA（批判思维、问题解决、写作三模块，10 月 12–16 日考试）；须提交一篇不超过 2000 字的论证性历史论文；12 月线上面试；UCAS LV21',
    qs: ['history', 'politics'],
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/history-and-politics' },




  // ═══════════ 剑桥 Cambridge（Minimum offer level=多数学院标准条件，实际录取普遍更高；offer 由各学院发出） ═══════════
  { school: 'cambridge', dirs: ['bio', 'physics'], zh: '自然科学（生物/化学/物理均在此一门）', en: 'Natural Sciences',
    degree: 'BA (Hons) / MSci · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776）', test: 'ESAT',
    alevelNote: '数学 + 另 2 门科学/数学科目', offer: 'college', note: '申请时须选 Biological 或 Physical 流；实际录取约 76%（生物）/97%（物理）达 A*A*A*',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/natural-sciences-ba-hons-msci' },

  { school: 'cambridge', dirs: ['eng', 'bio'], zh: '化学工程与生物技术', en: 'Chemical Engineering and Biotechnology',
    degree: 'BA (Hons) / MEng · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'ESAT',
    alevelNote: '数学 + 化学 + 第三门科学/数学', offer: 'college', note: 'ESAT',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/chemical-engineering-biotechnology-ba-hons-meng' },

  { school: 'cambridge', dirs: ['eng'], zh: '工程', en: 'Engineering',
    degree: 'BA (Hons) / MEng · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'ESAT',
    alevelNote: '数学 + 物理；学校开高数须至 AS/A；多数学院 A* 落数学/高数', offer: 'college', note: 'Churchill/Selwyn 等学院更高；Peterhouse 申请人可能另加 STEP II grade 2',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/engineering-ba-hons-meng' },

  { school: 'cambridge', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BA (Hons) · 3 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'TMUA',
    alevelNote: '数学为唯一必修；6 所学院另要求高数', offer: 'college', note: '实际约 80% 录取者 A*A*A*',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/economics-ba-hons' },

  { school: 'cambridge', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BA (Hons) / MEng · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'TMUA',
    alevelNote: '数学必修；高数须至 AS/A（学校开设时）；多数学院 A* 在数学/高数', offer: 'college', note: '2027 此课用 TMUA 而非 ESAT；申 Peterhouse/Trinity 另考 CSAT；2025 cycle 约 14 人/位',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/computer-science-ba-hons-meng' },

  { school: 'cambridge', dirs: ['stats'], zh: '数学（含统计路线）', en: 'Mathematics',
    degree: 'BA (Hons) / MMath · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'STEP',
    alevelNote: '数学 + 高数必修；学院常要求 A* 在数学/高数', offer: 'college', note: 'offer 附加 STEP 2&3 各 grade 1（录取后考）；flexible-offer 学院可 A*A*A*+单 STEP grade 1 替代；申请阶段全体考 TMUA',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/mathematics-ba-hons-mmath' },

  { school: 'cambridge', dirs: ['bio'], zh: '医学', en: 'Medicine',
    degree: 'MB, BChir · 6 年', alevel: 'A*A*A', ib: '41–42（HL 776）', test: 'UCAT',
    alevelNote: '化学必修 + 1 或 2 门科学/数学；多数学院要求化学 A*', offer: 'college', note: '实际多数录取 44+/HL777',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/medicine-mb-bchir' },

  { school: 'cambridge', dirs: ['econ'], zh: '环境、法律与经济（原土地经济）', en: 'Environment, Law, and Economics',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修科目（推荐经济与数学）', offer: 'college', note: '商科直申课程；官方课程名已更新为 Environment, Law and Economics；无考试，部分学院要书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/environment-law-economics-ba-hons' },




// ── 剑桥 · 社科 / 教育 / 人文（仅法学要 LNAT，其余无笔试，改为面试 + 书面作品） ──
  { school: 'cambridge', dirs: ['social'], zh: '法学', en: 'Law',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: 'LNAT',
    alevelNote: '无必修科目', offer: 'college',
    note: 'LNAT；部分学院另要求提交书面作品（Pembroke 需 2 篇）',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/law-ba-hons' },

  { school: 'cambridge', dirs: ['social'], zh: '人文、社会与政治科学（HSPS）', en: 'Human, Social, and Political Sciences',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修；建议英语、历史、古代 / 现代语言', offer: 'college',
    note: '无笔试；须提交 2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/human-social-political-sciences-ba-hons' },

  { school: 'cambridge', dirs: ['social'], zh: '心理与行为科学（PBS）', en: 'Psychological and Behavioural Sciences',
    degree: 'BA (Hons) · 3 年', alevel: 'A*A*A', ib: '41–42（HL 776）', test: '',
    alevelNote: '须至少一门数学/生物/化学/计算机科学/物理；部分学院指定科目', offer: 'college',
    note: '无笔试；部分学院要求 1–2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/psychological-behavioural-sciences-ba-hons' },

  { school: 'cambridge', dirs: ['social'], zh: '地理学', en: 'Geography',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '部分学院要求特定科目（如地理）', offer: 'college',
    note: '无笔试；通常无须提交书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/geography-ba-hons' },

  { school: 'cambridge', dirs: ['edu'], zh: '教育学', en: 'Education',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修；建议英语、历史、语言、社科科目', offer: 'college',
    note: '无笔试；须提交 2 份书面作品；部分学院不招此课',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/education-ba-hons' },

  { school: 'cambridge', dirs: ['arts'], zh: '历史学', en: 'History',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '必修历史', offer: 'college',
    note: '无笔试；须提交 2 份书面作品（Sidney Sussex 为 1 份）',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/history-ba-hons' },

  { school: 'cambridge', dirs: ['arts'], zh: '哲学', en: 'Philosophy',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修；建议数学、宗教研究、哲学、英语、历史、语言', offer: 'college',
    note: '无笔试；Downing 与圣约翰学院须提交 2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/philosophy-ba-hons' },

  { school: 'cambridge', dirs: ['arts'], zh: '英语', en: 'English',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '必修英语文学（或英语语言与文学）', offer: 'college',
    note: '无笔试；须提交 2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/english-ba-hons' },

  { school: 'cambridge', dirs: ['arts'], qs: [], zh: '古典学', en: 'Classics',
    degree: 'BA (Hons) · 3 或 4 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修（部分学院有额外科目要求）', offer: 'college',
    note: '无笔试；3 年与 4 年课均须提交 2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/classics-ba-hons' },

  { school: 'cambridge',
    dirs: ['social'],
    zh: '考古学',
    en: 'Archaeology BA',
    degree: 'BA · 3 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '无特定科目要求',
    test: '',
    offer: 'college',
    note: '覆盖考古、生物人类学、埃及学与亚述学',
    qs: [],
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/archaeology-ba-hons' },

  { school: 'cambridge',
    dirs: ['arts'],
    zh: '现代与中世纪语言',
    en: 'Modern and Medieval Languages',
    degree: 'BA · 4 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '须有至少一门所选语言达 A-level / IB HL；法语申请者须有法语 A-level；推荐另一门语言、英语、历史、数学',
    test: '',
    offer: 'college',
    note: '各学院均设面试前书面评估（无需提前报名）；须提交两篇书面作品，其一须为所修语言；4 年含海外一年',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/modern-medieval-languages-ba-hons' },

  { school: 'cambridge',
    dirs: ['arts'],
    zh: '音乐',
    en: 'Music',
    degree: 'BA · 3 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '须有 Music A-level / IB HL，或 ABRSM 乐理 8 级 Merit 以上',
    test: '',
    offer: 'college',
    note: '部分学院设面试评估（无需提前报名）；须提交书面作品与音乐材料（音乐史/分析论文、技术练习和/或本人作品）',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/music-ba-hons' },

  { school: 'cambridge',
    dirs: ['arts'],
    zh: '艺术史',
    en: 'History of Art',
    degree: 'BA · 3 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '无必修科目（接受 Art & Design）；多数学院要求论文类科目或语言达 A*/7；推荐历史、艺术史、英语、语言',
    test: '',
    offer: 'college',
    note: '无入学评估；Clare、Downing、Peterhouse、Robinson 学院另要求提交两篇书面作品',
    qs: ['art-design'],
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/history-of-art-ba-hons' },

  { school: 'cambridge',
    dirs: ['arts'],
    zh: '亚洲与中东研究',
    en: 'Asian and Middle Eastern Studies',
    degree: 'BA · 4 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '无必修科目；若与欧洲语言合修，须该语言达 A-level / IB HL；推荐英语、历史、语言',
    test: '',
    offer: 'college',
    note: '仅在与欧洲语言合修时各学院设面试前评估（无需提前报名）；部分学院要求书面作品；4 年含海外一年',
    qs: ['modern-languages'],
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/asian-middle-eastern-studies-ba-hons' },

  { school: 'cambridge',
    dirs: ['arts'],
    zh: '神学、宗教与宗教哲学',
    en: 'Theology, Religion and Philosophy of Religion',
    degree: 'BA · 3 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '无必修科目；推荐论文类科目、宗教研究、英语、历史、语言',
    test: '',
    offer: 'college',
    note: '无入学评估；须提交两篇书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/theology-religion-philosophy-of-religion-ba-hons' },

  { school: 'cambridge',
    dirs: ['arts'],
    zh: '历史与现代语言',
    en: 'History and Modern Languages',
    degree: 'BA · 4 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '须有 History A-level / IB HL；若续修所选语言须其 A-level / IB HL；法语以外可从零起点学',
    test: '',
    offer: 'college',
    note: '各学院均设面试前评估（无需提前报名）；须提交两篇书面作品（其一为历史论文，另一为所修语言或英语）；4 年含海外一年',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/history-modern-languages-ba-hons' },

  { school: 'cambridge',
    dirs: ['arts', 'social'],
    zh: '历史与政治',
    en: 'History and Politics',
    degree: 'BA · 3 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '须有 History A-level / IB HL',
    test: '',
    offer: 'college',
    note: '部分学院设面试评估（无需提前报名）；须提交两篇书面作品',
    qs: ['history', 'politics'],
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/history-politics-ba-hons' },




  // ═══════════ 帝国理工 Imperial（/2027/ 版官方页；工程系普遍 ESAT，数学/计算机 TMUA） ═══════════
  { school: 'imperial', dirs: ['bio'], zh: '医学生物科学', en: 'Medical Biosciences',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 生物 6 + 相关科 6）', test: '',
    alevelNote: '生物 A + 化学/数学/高数/物理之一 A', offer: 'min', note: '最低档与典型档相同；无笔试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/medical-biosciences/' },

  { school: 'imperial', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 化学 6 + 相关科）', test: 'ESAT',
    alevelNote: '化学 A + 生物/数学/物理之一 A', offer: 'min', note: '2027 须考 ESAT',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/biochemistry-bsc/' },

  { school: 'imperial', dirs: ['bio'], zh: '生物科学', en: 'Biological Sciences',
    degree: 'BSc / MSci · 3–4 年', alevel: 'AAA', ib: '38（HL 生物 6 + 相关科）', test: 'ESAT',
    alevelNote: '生物 A + 化学/数学/物理之一 A', offer: 'min', note: '2027 起须 ESAT',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/biological-sciences/' },

  { school: 'imperial', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 化学+数学各 6）', test: '',
    alevelNote: '化学 A、数学 A', offer: 'min', note: '典型A*AA；无笔试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/chemistry-bsc/' },

  { school: 'imperial', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '40（HL 数学 7、物理 7）', test: 'ESAT',
    alevelNote: '数学 A*、物理 A*', offer: 'min', note: '典型A*A*A',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/physics-bsc/' },

  { school: 'imperial', dirs: ['eng'], zh: '航空工程', en: 'Aeronautical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学 7、物理 7）', test: 'ESAT',
    alevelNote: '数学 A*、物理 A*（3 科制须 A*）', offer: 'min', note: '典型A*A*A*',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/aeronautical-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '机械工程', en: 'Mechanical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学、物理各 6）', test: 'ESAT',
    alevelNote: '数学 A*；物理 3 科制须 A*', offer: 'min', note: '典型A*A*A*',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/mechanical-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '电子与电气工程', en: 'Electrical and Electronic Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学 7、物理 7）', test: 'ESAT',
    alevelNote: '数学 A*、物理 A*', offer: 'min', note: '典型A*A*A；官方名为 Electrical and Electronic',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/electrical-electronic-engineering-meng/' },

  { school: 'imperial', dirs: ['eng'], zh: '土木工程', en: 'Civil Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学 7、物理 6）', test: 'ESAT',
    alevelNote: '数学 A*、物理 A*', offer: 'min', note: '典型A*A*A/A*AAA',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/civil-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '化学工程', en: 'Chemical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学 7、化学 7）', test: 'ESAT',
    alevelNote: '化学 A*、数学 A*', offer: 'min', note: '典型A*A*A',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/chemical-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '设计工程', en: 'Design Engineering',
    degree: 'MEng · 4 年', alevel: 'A*AA', ib: '39（HL 数学 7 + 一科 6）', test: 'ESAT',
    alevelNote: '数学 A* + 两门 AA', offer: 'min', note: '典型A*AA；戴森设计学院',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/design-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '生物医学工程', en: 'Biomedical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*AA', ib: '39（HL 数学 6、物理 6）', test: '',
    alevelNote: '数学 A*、物理 A、第三科 A', offer: 'min', note: '页面未列笔试（与其他工程系不同，留意）',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/biomedical-engineering/' },

  { school: 'imperial', dirs: ['econ'], zh: '经济学、金融与数据科学', en: 'Economics, Finance and Data Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 数学 7 + 两门 6）', test: 'TMUA',
    alevelNote: '数学 A*', offer: 'min', note: '商学院本科；TMUA + 线上面试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/economics-finance-data-science/' },

  { school: 'imperial', dirs: ['cs'], zh: '计算机', en: 'Computing',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '41（HL 数学 7 + 相关科 7）', test: 'TMUA',
    alevelNote: '数学 A*', offer: 'min', note: '典型A*A*A；TMUA + 面试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/computing-meng/' },

  { school: 'imperial', dirs: ['cs'], zh: '计算机（三年制）', en: 'Computing',
    degree: 'BEng · 3 年', alevel: 'A*A*A', ib: '41（HL 数学 7 + 相关科 7）', test: 'TMUA',
    alevelNote: '数学 A*', offer: 'min', note: '与 Computing MEng 同系同要求；TMUA + 面试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/computing-beng/' },

  { school: 'imperial', dirs: ['stats'], zh: '数学', en: 'Mathematics',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 7）', test: 'TMUA',
    alevelNote: '数学 A* + 高数 A*', offer: 'min', note: '典型A*A*A；数学系各方向要求一致',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/mathematics-bsc/' },




  // ═══════════ LSE（社科院校，本页收录经管与数学类；多门须 TMUA） ═══════════
  { school: 'lse', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 7）', test: 'TMUA',
    alevelNote: '数学 A* 必修；高数强烈建议', offer: 'typical', note: 'TMUA 必考；高数未修不受损',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics' },

  { school: 'lse', dirs: ['econ'], zh: '计量与数理经济', en: 'Econometrics and Mathematical Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 7）', test: 'TMUA',
    alevelNote: '数学 A*', offer: 'typical', note: 'TMUA 必考',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-econometrics-and-mathematical-economics' },

  { school: 'lse', dirs: ['econ'], zh: '金融学', en: 'Finance',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 7）', test: '',
    alevelNote: '数学 A*', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-finance' },

  { school: 'lse', dirs: ['econ'], zh: '会计与金融', en: 'Accounting and Finance',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 6）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: 'A-level Accounting 可算传统科目但非必需',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-accounting-and-finance' },

  { school: 'lse', dirs: ['econ', 'cs'], zh: '经济学与数据科学', en: 'Economics and Data Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: '2026 新开；TMUA 鼓励；物理/化学等量化科目为良好准备',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics-and-data-science' },

  { school: 'lse', dirs: ['econ'], zh: '管理学', en: 'Management',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766、含数学）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: '偏爱文理混合科目组合',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-management' },

  { school: 'lse', dirs: ['cs'], zh: '数据科学', en: 'Data Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-data-science' },

  { school: 'lse', dirs: ['stats'], zh: '精算科学', en: 'Actuarial Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-actuarial-science' },

  { school: 'lse', dirs: ['stats'], zh: '金融数学与统计', en: 'Financial Mathematics and Statistics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-financial-mathematics-and-statistics' },

  { school: 'lse', dirs: ['stats', 'econ'], zh: '数学与经济', en: 'Mathematics with Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-mathematics-with-economics' },

  { school: 'lse', dirs: ['stats'], zh: '数学、统计与商务', en: 'Mathematics, Statistics and Business',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-mathematics-statistics-and-business' },




// ── LSE · 社科核心（LSE 本就是社科专门院校；法学 LNAT，其余无笔试、无面试） ──
  { school: 'lse', dirs: ['social'], zh: '法学（法学士）', en: 'LLB Bachelor of Laws',
    degree: 'LLB · 3 年', alevel: 'A*AA', ib: '39（HL 766）', test: 'LNAT',
    alevelNote: '无必修科目；看重阅读写作与论文类科目（历史、英语、经济等）', offer: 'typical',
    note: '所有申请者须考 LNAT',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/llb-bachelor-of-laws' },

  { school: 'lse', dirs: ['social'], zh: '社会学', en: 'BSc Sociology',
    degree: 'BSc · 3 年', alevel: 'AAB', ib: '37（HL 666）', test: '',
    alevelNote: '无必修科目；典型含社会学、心理学、历史、政治、宗教、英语，英语类科目尤其受重视', offer: 'typical',
    note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-sociology' },

  { school: 'lse', dirs: ['social'], zh: '政治学', en: 'BSc Politics',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766）', test: '',
    alevelNote: '无必修科目；典型含政治、历史、英语、经济、社会学、哲学', offer: 'typical',
    note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-politics' },

  { school: 'lse', dirs: ['social'], zh: '政治与经济', en: 'BSc Politics and Economics',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766，含数学）', test: '',
    alevelNote: '数学必修', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-politics-and-economics' },

  { school: 'lse', dirs: ['social'], zh: '国际关系', en: 'BSc International Relations',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766）', test: '',
    alevelNote: '无必修科目；偏好至少两门传统学术科目', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-international-relations' },

  { school: 'lse', dirs: ['social'], zh: '心理与行为科学', en: 'BSc Psychological and Behavioural Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766，含科学/数学/心理学之一）', test: '',
    alevelNote: '须生物/化学/物理/数学/心理学中至少一门达 A', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-psychological-and-behavioural-science' },

  { school: 'lse', dirs: ['social'], zh: '社会人类学', en: 'BA Social Anthropology',
    degree: 'BA · 3 年', alevel: 'AAB', ib: '37（HL 666）', test: '',
    alevelNote: '无必修科目；偏好文理兼修的广泛选课', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/ba-social-anthropology' },

  { school: 'lse', dirs: ['social'], zh: '地理学', en: 'BA Geography',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '38（HL 766）', test: '',
    alevelNote: '无必修科目；地理与经济为最常见选课', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/ba-geography' },

  { school: 'lse', dirs: ['social'], zh: '经济史', en: 'BSc Economic History',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766，含经济或历史）', test: '',
    alevelNote: '经济或历史须选其一', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economic-history' },

  { school: 'lse', dirs: ['social', 'arts'], zh: '哲学、政治与经济', en: 'BSc Philosophy, Politics and Economics',
    degree: 'BSc · 4 年', alevel: 'A*AA', ib: '39（HL 766，数学 7）', test: '',
    alevelNote: '数学必修，通常须 A*（或高数 A* + 数学 A）', offer: 'typical',
    note: '四年制，第四年含外部客户实践项目',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-philosophy-politics-and-economics' },

  { school: 'lse',
    dirs: ['social'],
    zh: '国际社会与公共政策',
    en: 'BSc International Social and Public Policy',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '37（HL 666）',
    alevelNote: 'GCSE 英语与数学不低于 B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L400；社会政策系；contextual A-level BBB / IB 35',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-international-social-and-public-policy' },

  { school: 'lse',
    dirs: ['social'],
    zh: '政治与哲学',
    en: 'BSc Politics and Philosophy',
    degree: 'BSc · 3 年',
    alevel: 'AAA',
    ib: '38（HL 766）',
    alevelNote: 'GCSE 英语与数学不低于 B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS LV25；政府系；contextual A-level AAB / IB 37',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-politics-and-philosophy' },




  // ═══════════ UCL（新版 /courses/ 课程页；官网有反爬，链接与分数经官网+UCAS 核对） ═══════════
  { school: 'ucl', dirs: ['bio'], zh: '生物医学', en: 'Biomedical Sciences',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 生物+化学各 6）', test: '',
    alevelNote: '生物 + 化学须 AA', offer: 'typical', note: '无笔试；GCSE 英语+数学 B/6',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/biomedical-sciences-bsc' },

  { school: 'ucl', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 18、无低于 5）', test: '',
    alevelNote: '化学必修', offer: 'typical', note: '',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/biochemistry-bsc' },

  { school: 'ucl', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 18、化学 6）', test: '',
    alevelNote: '化学 A + 生物/物理/数学之一 A', offer: 'typical', note: 'GCSE 英语 C/4、数学 B/6',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/chemistry-bsc' },

  { school: 'ucl', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7 + 物理 6）', test: '',
    alevelNote: '数学与物理 A*A（不分先后）', offer: 'typical', note: '无额外笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/physics-bsc' },

  { school: 'ucl', dirs: ['eng'], zh: '机械工程', en: 'Mechanical Engineering',
    degree: 'MEng · 4 年（另 3 年 BEng）', alevel: 'A*AA', ib: '39（HL 19、数学+物理 7,6）', test: 'TARA',
    alevelNote: '数学与物理必修，A* 落其一', offer: 'typical', note: '2027 官网列为 TARA（第一轮核验时尚未定稿）',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/mechanical-engineering-meng' },

  { school: 'ucl', dirs: ['eng'], zh: '土木工程', en: 'Civil Engineering',
    degree: 'MEng · 4 年（另 3 年 BEng）', alevel: 'A*AA', ib: '39（HL 19、物理须 SL/HL）', test: '',
    alevelNote: '至少两门 UCL 优先科目，建议数学/物理', offer: 'typical', note: '无笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/civil-engineering-meng' },

  { school: 'ucl', dirs: ['eng'], zh: '电子与电气工程', en: 'Electronic and Electrical Engineering',
    degree: 'BEng · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: 'ESAT',
    alevelNote: '数学 A*；物理或高数优先', offer: 'typical', note: 'IET 认证；ESAT',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/electronic-and-electrical-engineering-beng' },

  { school: 'ucl', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc (Econ) · 3 年', alevel: 'A*AA', ib: '39（HL 数学 7）', test: 'TMUA',
    alevelNote: '数学必修且 A*', offer: 'typical', note: '2027 起须考 TMUA；不收重考',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/economics-bsc-econ' },

  { school: 'ucl', dirs: ['econ'], zh: '管理科学', en: 'Management Science',
    degree: 'BSc · 3 年（另 4 年 MSci）', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: '',
    alevelNote: '数学 A*', offer: 'typical', note: 'GCSE 英语 B/6',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/management-science-bsc' },

  { school: 'ucl', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '40（HL 20、数学 7）', test: 'TARA',
    alevelNote: '数学或高数 A*', offer: 'typical', note: 'CS 系全部本科须考 TARA',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/computer-science-bsc' },

  { school: 'ucl', dirs: ['cs'], zh: '计算机科学（四年制）', en: 'Computer Science',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 20、数学 7）', test: 'TARA',
    alevelNote: '“AAA 且数学 A*”或“数学 A + 高数 A*”', offer: 'typical', note: '含 Study Abroad / Year in Industry 变体；TARA',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/computer-science-meng' },

  { school: 'ucl', dirs: ['cs', 'stats'], zh: '数据科学（属统计系）', en: 'Data Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: '',
    alevelNote: 'A* 必须数学；高数偏好', offer: 'typical', note: 'RSS 认证、2023 新设；属统计科学系',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/data-science-bsc' },

  { school: 'ucl', dirs: ['stats'], zh: '统计科学', en: 'Statistics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: '',
    alevelNote: '数学 A*；高数优先', offer: 'typical', note: '无笔试无面试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/statistics-bsc' },

  { school: 'ucl', dirs: ['stats', 'econ'], zh: '统计、经济与金融', en: 'Statistics with Economics and Finance',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: '',
    alevelNote: 'A* 必须数学；高数偏好', offer: 'typical', note: '统计系不收重考；无笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/statistics-economics-and-finance-bsc' },

  { school: 'ucl',
    dirs: ['edu'],
    zh: '教育学、社会与文化',
    en: 'Education, Society and Culture BA',
    degree: 'BA · 3 年',
    alevel: 'ABB',
    ib: '34（HL 16）',
    alevelNote: '无特定必修科目；优先社会科学、古典学、英语文学/语言或商科；至少两门 A level 须取自 UCL 认可科目清单。GCSE：English Language B/6，Mathematics C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS X300；UCL 教育学院（IOE，QS 教育学科连续多年全球第 1）本科旗舰专业，由 Education, Practice and Society 系开设；contextual BBB；官网保留面试权',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/education-society-and-culture-ba' },

  { school: 'ucl',
    dirs: ['edu'],
    zh: '幼儿教育',
    en: 'Early Childhood Education BA',
    degree: 'BA · 3 年',
    alevel: 'ABB',
    ib: '34（HL 16）',
    alevelNote: '无特定必修科目；至少两门 A level 须取自 UCL 认可科目清单。GCSE：English Language 与 Mathematics 均需 C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS X302；IOE 教育学院 Learning and Leadership 系开设；contextual BBB；毕业时可获面试机会申请 EYITT 早期教育教师资格培训',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/early-childhood-education-ba' },

  { school: 'ucl',
    dirs: ['edu', 'social'],
    zh: '心理学与教育学',
    en: 'Psychology with Education BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAA',
    ib: '38（HL 18）',
    alevelNote: '无必修科目；Psychology/Sociology/Mathematics/Biology 中一门或以上优先；至少两门 A level 取自 UCL 认可清单。GCSE：English Language 与 Mathematics 均需 B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS C801；IOE 开设，获英国心理学会（BPS）认证；contextual ABB',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/psychology-education-bsc' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '心理学',
    en: 'Psychology BSc',
    degree: 'BSc · 3 年',
    alevel: 'A*AA',
    ib: '39（HL 19）',
    alevelNote: '须含两门取自 Biology/Chemistry/Mathematics/Physics/Psychology 的 A*A；IB 为 HL 总分 19，且两门相关科目达 7 与 6。GCSE：English Language、Mathematics 及两门科学（双奖可）grade B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS C800；由心理学与语言科学部开设，获 BPS 认证；contextual A*AC',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/psychology-bsc' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '社会学',
    en: 'Sociology BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '36（HL 17）',
    alevelNote: '无特定科目；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language 与 Mathematics 均需 B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L301；由 Social Research Institute（IOE）开设；contextual BBB。2027 入学不再要求 TARA 笔试（该笔试仅适用于 2026 入学一轮）',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/sociology-bsc' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '法学',
    en: 'Law LLB',
    degree: 'LLB · 3 年',
    alevel: 'A*AA',
    ib: '39（HL 19）',
    alevelNote: '无特定科目；至少两门 A level 取自 UCL 认可清单；不接受重考（resits）。GCSE：English Language 与 Mathematics 均需 B/6',
    test: 'LNAT',
    offer: 'typical',
    note: 'UCAS M100；UCL Laws 开设，所有申请者须考 LNAT；contextual AAB；英语要求为全校最高档之一',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/law-llb' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '政治与国际关系',
    en: 'Politics and International Relations BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAA',
    ib: '38（HL 18）',
    alevelNote: '无特定科目，偏好论文类科目（非必须）；至少两门 A level 取自 UCL 认可清单。GCSE：English Language B/6，Mathematics C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS L251；由政治学系（Political Science）开设；contextual ABB',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/politics-and-international-relations-bsc' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '地理学',
    en: 'Geography BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '36（HL 17）',
    alevelNote: '无特定科目；至少两门 A level 取自 UCL 认可清单。GCSE：English Language 与 Mathematics 均需 C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS F800；由地理系开设；contextual BBB',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/geography-bsc' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '人类学',
    en: 'Anthropology BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '36（HL 17）',
    alevelNote: '无必修科目；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language 与 Mathematics 需 C/4，且 Biology/Chemistry/Physics 或 Double Science 需 B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L602；人类学系开设；contextual BBB（IB 32）；无入学笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/anthropology-bsc' },

  { school: 'ucl',
    dirs: ['arts'],
    zh: '哲学',
    en: 'Philosophy BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '38（HL 18）',
    alevelNote: '无必修科目；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language B/6，Mathematics C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS V500；哲学系开设；contextual ABB（IB 34）；无入学笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/philosophy-ba' },

  { school: 'ucl',
    dirs: ['arts'],
    zh: '哲学与经济学',
    en: 'Philosophy and Economics BA',
    degree: 'BA · 3 年',
    alevel: 'A*AA',
    ib: '39（HL 19、数学 7）',
    alevelNote: 'Mathematics 必修且需 A*；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language B/6，Mathematics C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS VL51；哲学系开设；contextual A*BB（IB 36、数学 7）；无入学笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/philosophy-and-economics-ba' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '社会科学',
    en: 'Social Sciences BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '36（HL 17）',
    alevelNote: '无必修科目；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language 与 Mathematics 需 B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L300；由 Social Research Institute（IOE）开设；contextual BBB（IB 32）；2027 入学不再要求 TARA 笔试（TARA 仅适用于 2026 入学一轮）',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/social-sciences-bsc' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '社会学与科学政治',
    en: 'Sociology and Politics of Science BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '36（HL 17）',
    alevelNote: '无必修科目；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language 与 Mathematics 需 C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS L391；由 Science and Technology Studies 系开设；contextual BBB（IB 32）；无入学笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/sociology-and-politics-science-bsc' },

  { school: 'ucl',
    dirs: ['social'],
    zh: '欧洲社会与政治研究',
    en: 'European Social and Political Studies BA',
    degree: 'BA · 4 年',
    alevel: 'A*AA',
    ib: '39（HL 19）',
    alevelNote: '偏好人文或社科科目（或 Mathematics）；如选纯 Economics 方向，Mathematics 须 A*；如 Spanish 作主修语言，须 A。GCSE：English Language B/6，Mathematics C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS R990；四年制；由 European and International Social and Political Studies 系开设；须参加 UCL 自设线上 Thinking Skills Test（TST，10 月至次年 2 月每月一场），原 TARA 已取消；contextual A*AB 或 AAB',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/european-social-and-political-studies-ba' },

  { school: 'ucl',
    dirs: ['arts'],
    zh: '艺术史',
    en: 'History of Art BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '36（HL 17）',
    alevelNote: '偏好论文类（essay-based）科目；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language 与 Mathematics 需 C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS V350；艺术史系开设（1965 年建系）；contextual ABC（IB 32）；无入学笔试',
    qs: ['art-design'],
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/history-art-ba' },

  { school: 'ucl',
    dirs: ['arts'],
    zh: '比较文学',
    en: 'Comparative Literature BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '38（HL 18、人文科目 6）',
    alevelNote: '须含一门人文（Humanities）科目；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language B/6，Mathematics C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS Q200；由 School of European Languages, Culture and Society（SELCS）开设；contextual ABB（IB 34）；无入学笔试',
    qs: ['modern-languages'],
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/comparative-literature-ba' },

  { school: 'ucl',
    dirs: ['arts'],
    zh: '历史学',
    en: 'History BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '38（HL 18、历史 6）',
    alevelNote: 'History 必修；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language B/6，Mathematics C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS V100；历史系开设；contextual ABB（IB 34、历史 6）；无入学笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/history-ba' },

  { school: 'ucl',
    dirs: ['arts'],
    zh: '语言学',
    en: 'Linguistics BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '36（HL 17）',
    alevelNote: '偏好 English Language；至少两门 A level 取自 UCL 认可科目清单。GCSE：English Language B/6，Mathematics C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS Q100；由 Division of Psychology and Language Sciences 开设；contextual BBB（IB 32）；无入学笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/linguistics-ba' },

  { school: 'ucl',
    dirs: ['media'],
    zh: '媒体',
    en: 'Media BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '36（HL 17）',
    alevelNote: '优先科目：艺术与人文学科或计算机科学；至少两门 A level 须取自 UCL 认可科目清单。IB：三门 HL 合计 17 且单科不低于 5。GCSE：English Language 与 Mathematics 均需 C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS P300；UCL 教育学院（IOE）Culture, Communication and Media 系开设，伦敦 Stratford（UCL East）校区；contextual BBB；所有申请人须提交作品集（一份 PDF，最多 6 件作品、12 页）',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/media-ba' },




  // ═══════════ KCL（成绩在 /requirements 子页） ═══════════
  { school: 'kcl', dirs: ['bio'], zh: '生物医学', en: 'Biomedical Science',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 生物+化学各 6）', test: '',
    alevelNote: '生物与化学各 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/biomedical-science-bsc/entry-requirements' },

  { school: 'kcl', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 生物+化学各 6）', test: '',
    alevelNote: '生物与化学各 A', offer: 'typical', note: '与 Biomedical Science 同档',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/biochemistry-bsc/requirements' },

  { school: 'kcl', dirs: ['bio'], zh: '药学', en: 'Pharmacy',
    degree: 'MPharm · 4 年', alevel: 'AAA', ib: '36（HL 化学 6 + 相关 6）', test: '',
    alevelNote: '化学 A + 生物/数学/物理之一 A；GCSE 英语+数学 6/B', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/pharmacy-mpharm/requirements' },

  { school: 'kcl', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 数学 AA+物理各 6）', test: '',
    alevelNote: '数学与物理各 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/physics-bsc/requirements' },

  { school: 'kcl', dirs: ['eng'], zh: '通用工程', en: 'General Engineering',
    degree: 'BEng · 3 年', alevel: 'AAA', ib: '36（HL 数学 AA 6）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: '同系另有电子/生物医学工程同档',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/general-engineering-beng/entry-requirements' },

  { school: 'kcl', dirs: ['eng'], zh: '电子工程', en: 'Electronic Engineering',
    degree: 'BEng · 3 年', alevel: 'AAA', ib: '36（HL 数学 AA 6）', test: '',
    alevelNote: '数学 A；另需理科实践考核', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/electronic-engineering-beng/requirements' },

  { school: 'kcl', dirs: ['eng'], zh: '生物医学工程', en: 'Biomedical Engineering',
    degree: 'BEng · 3 年', alevel: 'AAA', ib: '36（HL 相关 6）', test: '',
    alevelNote: '数学 A + 生物/化学/CS/高数/物理之一 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/biomedical-engineering-beng/requirements' },

  { school: 'kcl', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 6）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/economics-bsc/requirements' },

  { school: 'kcl', dirs: ['econ'], zh: '经济与管理', en: 'Economics and Management',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 6 + HL 人文/社科 6）', test: '',
    alevelNote: '数学 A + 一门人文/社科 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/economics-and-management-bsc/requirements' },

  { school: 'kcl', dirs: ['econ'], zh: '商业管理', en: 'Business Management',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 人文/社科 6）', test: '',
    alevelNote: '须含一门人文/社科 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/business-management-bsc/entry-requirements' },

  { school: 'kcl', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 6）', test: '',
    alevelNote: '数学或高数 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/computer-science-bsc/requirements' },

  { school: 'kcl', dirs: ['cs'], zh: '人工智能', en: 'Artificial Intelligence',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 6）', test: '',
    alevelNote: '数学或高数 A', offer: 'typical', note: 'Informatics 旗舰',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/artificial-intelligence-bsc/requirements' },

  { school: 'kcl', dirs: ['stats'], zh: '数学与统计', en: 'Mathematics with Statistics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 AA 7）', test: '',
    alevelNote: '数学 A* + 高数 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/mathematics-with-statistics-bsc/entry-requirements' },

  { school: 'kcl', dirs: ['stats'], zh: '数学', en: 'Mathematics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 AA 7）', test: '',
    alevelNote: '数学+高数合计 A*A（未学高数可用 AS 高数 A）', offer: 'typical', note: '高数近乎必选',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/mathematics-bsc/requirements' },

  { school: 'kcl',
    dirs: ['edu', 'social'],
    zh: '社会科学',
    en: 'Social Sciences BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL 17）',
    alevelNote: '无必修科目，偏好至少一门社会科学科目（如社会学、政治、经济、心理等）。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L300；隶属教育、传播与社会学院（School of Education, Communication & Society, ECS）——KCL 以 ECS 学院本科专业代表教育/社科方向；社会学与政策方向《卫报》2026 排名英国第 3；contextual BBB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/social-sciences-ba' },

  { school: 'kcl',
    dirs: ['arts'],
    zh: '英语语言与语言学',
    en: 'English Language and Linguistics BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL 17）',
    alevelNote: '须含一门取自 English Language/English Literature/Creative Writing/Modern Foreign Language/Psychology 的 A；IB 需对应科目 HL 6。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS Q100；隶属 ECS 学院；QS 2026 学科排名英语语言与文学英国第 5；contextual ABC',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/english-language-and-linguistics-ba' },

  { school: 'kcl',
    dirs: ['arts'],
    zh: '文理学科',
    en: 'Liberal Arts BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36（HL 18）',
    alevelNote: '无必修科目（选择音乐主修者须有 Music A level 或 Grade 5 乐理）；GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS LP99；跨学科文理学位，可自选主修组合（含现代语言，为四年制）；contextual ABB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/liberal-arts-ba' },

  { school: 'kcl',
    dirs: ['social'],
    zh: '战争研究',
    en: 'War Studies BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36（HL 18）',
    alevelNote: '无必修/偏好科目。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L252；由战争研究系（Department of War Studies）开设，为 KCL 招牌方向；三年制，可选一年海外交换；contextual ABB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/war-studies-ba' },

  { school: 'kcl',
    dirs: ['social'],
    zh: '国际关系',
    en: 'International Relations BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36（HL 18）',
    alevelNote: '无必修/偏好科目。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L250；由战争研究系（Department of War Studies）开设；contextual ABB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/international-relations-ba' },

  { school: 'kcl',
    dirs: ['social'],
    zh: '心理学',
    en: 'Psychology BSc',
    degree: 'BSc · 3 年',
    alevel: 'A*AA',
    ib: '38（HL 19）',
    alevelNote: '须含一门取自 Biology/Chemistry/Mathematics/Physics/Psychology 的 A；IB 需对应科目 HL 6；另有 GCSE Mathematics 要求（可用 IB Mathematics SL/HL grade 2 满足）',
    test: '',
    offer: 'typical',
    note: 'UCAS C800（另设含海外年/实习年版本）；由心理学系（IoPPN）开设，获 BPS 认证；contextual AAB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/psychology-bsc' },

  { school: 'kcl',
    dirs: ['social'],
    zh: '法学',
    en: 'Law LLB',
    degree: 'LLB · 3 年',
    alevel: 'A*AA',
    ib: '38（HL 19）',
    alevelNote: '无必修科目。GCSE：English Language B/6',
    test: 'LNAT',
    offer: 'typical',
    note: 'UCAS M100；Dickson Poon 法学院开设，所有申请者须于 12 月 31 日前完成 LNAT；contextual AAB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/law-llb' },

  { school: 'kcl',
    dirs: ['social'],
    zh: '政治经济学',
    en: 'Political Economy BA/BSc',
    degree: 'BA/BSc · 3 年',
    alevel: 'A*AA',
    ib: '38（HL 19）',
    alevelNote: '无必修科目。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L200；由政治经济系（Department of Political Economy）开设；QS 2026 政治学全球第 11、英国第 4；contextual AAB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/political-economy-ba-bsc' },

  { school: 'kcl',
    dirs: ['social'],
    zh: '地理学',
    en: 'Geography BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL 17）',
    alevelNote: '无必修/偏好科目。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L700；由地理系（Department of Geography）开设，隶属 School of Global Affairs（Faculty of Social Science & Public Policy）；同系另设物理地理方向的 Geography & Environmental Science BSc（UCAS F800），录取要求与本专业一致；可选海外交换年；contextual BBB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/geography-ba/requirements' },

  { school: 'kcl',
    dirs: ['social'],
    zh: '国际发展',
    en: 'International Development BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36（HL 18）',
    alevelNote: '无必修科目；偏好至少一门社会科学科目。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L900；由国际发展系（Department of International Development）开设；三年制，另设含一年海外的四年制版本；contextual ABB',
    qs: ['social-policy-administration'],
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/international-development-ba/requirements' },

  { school: 'kcl',
    dirs: ['social'],
    zh: '全球健康与社会科学',
    en: 'Global Health & Social Science BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL 17）',
    alevelNote: '无必修/偏好科目。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L511；由全球健康与社会科学系（Department of Global Health & Social Medicine）开设，隶属 School of Global Affairs；可四年制含一年海外；contextual BBB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/global-health-and-social-science-ba/requirements' },

  { school: 'kcl',
    dirs: ['arts'],
    zh: '哲学',
    en: 'Philosophy BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36（HL 18）',
    alevelNote: '无必修/偏好科目。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS V500；由哲学系（Department of Philosophy）开设；contextual ABB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/philosophy-ba/requirements' },

  { school: 'kcl',
    dirs: ['arts'],
    zh: '历史学',
    en: 'History BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36（HL 18）',
    alevelNote: '无必修科目；通常期望提交 History A level（或同等），未修者若在申请中清楚体现对历史学科的兴趣与投入亦可考虑。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS V100；由历史系（Department of History）开设；contextual ABB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/history-ba/requirements' },

  { school: 'kcl',
    dirs: ['arts'],
    zh: '古代史',
    en: 'Ancient History BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL 17）',
    alevelNote: '无必修科目；偏好 Classical Civilisation、Ancient History 或 History。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS Q806；由古典学系（Department of Classics）开设；contextual BBB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/ancient-history-ba/requirements' },

  { school: 'kcl',
    dirs: ['arts'],
    zh: '比较文学',
    en: 'Comparative Literature BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL 17）',
    alevelNote: '必修 English Literature 或 English Language & Literature 且达 A；偏好现代或古代语言科目。GCSE：无特定科目要求',
    test: '',
    offer: 'typical',
    note: 'UCAS Q200；由语言、文学与文化系（Department of Languages, Literatures and Cultures）开设；contextual ABC',
    qs: ['modern-languages'],
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/comparative-literature-ba/requirements' },

  { school: 'kcl',
    dirs: ['arts'],
    zh: '英语',
    en: 'English BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36（HL 18）',
    alevelNote: '必修 English Literature 或 English Language and Literature 且达 A。GCSE：English Language B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS Q300；由英语系（Department of English）开设；contextual ABB',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/english-ba/requirements' },

  { school: 'kcl',
    dirs: ['media'],
    zh: '电影研究',
    en: 'Film Studies BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL 17）',
    alevelNote: '须包含一门论文类（essay-based）学科；IB 亦须含论文类 HL。General Studies、Critical Thinking、Thinking Skills、Global Perspectives 不计入；contextual BBB',
    test: '',
    offer: 'typical',
    note: 'UCAS P303；电影研究系（Department of Film Studies）开设；以电影史、理论与批评为主，非电影制作',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/film-studies-ba/entry-requirements' },

  { school: 'kcl',
    dirs: ['media'],
    zh: '数字媒体与文化',
    en: 'Digital Media and Culture BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL 17）',
    alevelNote: '无必修科目；优先 Art and Design、English（文学或语言）、Communication and Culture、History、Media Studies、Philosophy 之一；contextual BBB',
    test: '',
    offer: 'typical',
    note: 'UCAS P390；数字人文系（Department of Digital Humanities）开设；含可选实习与海外交换',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/digital-media-culture-ba/requirements' },




  // ═══════════ 曼大 Manchester（2027 页；CS 已较 2026 下调） ═══════════
  { school: 'manchester', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAA–AAB', ib: '35（HL 6,6,5）', test: '',
    alevelNote: '含化学；另需生物/物理/数学之一 AB', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00521/bsc-biochemistry/' },

  { school: 'manchester', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '38（HL 7,7,6）', test: '',
    alevelNote: '物理 A* + 数学/高数 A*', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00638/bsc-physics/' },

  { school: 'manchester', dirs: ['eng'], zh: '机械工程', en: 'Mechanical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '38（HL 7,7,6）', test: '',
    alevelNote: '数学、物理 + 另 1 门', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03921/meng-mechanical-engineering/' },

  { school: 'manchester', dirs: ['eng'], zh: '电子与电气工程', en: 'Electrical and Electronic Engineering',
    degree: 'MEng · 4 年', alevel: 'A*AA', ib: '37（HL 7,6,6、数学 7）', test: '',
    alevelNote: '数学 A* + 物理/电子/高数/化学/CS 之一 A', offer: 'typical', note: 'BEng 版同存',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03894/meng-electrical-and-electronic-engineering/' },

  { school: 'manchester', dirs: ['eng'], zh: '航空航天工程', en: 'Aerospace Engineering',
    degree: 'MEng · 4 年', alevel: 'A*AA', ib: '37（HL 7,6,6）', test: '',
    alevelNote: '数学+物理+另 1 门（无物理个案可看高数）', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03826/meng-aerospace-engineering/' },

  { school: 'manchester', dirs: ['eng'], zh: '化学工程', en: 'Chemical Engineering',
    degree: 'MEng · 4 年', alevel: 'AAA', ib: '36（HL 6,6,6、数学仅 AA）', test: '',
    alevelNote: '数学 + 化学或物理', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03848/meng-chemical-engineering/' },

  // qs 钉空：本站收录的 37 个学科里没有「材料科学」，不钉就会退回整块工程方向桶，
  // 挂上一串化学工程 / 电子电气 / 土木的名次——对这个专业是误导。
  { school: 'manchester', dirs: ['eng'], qs: [], zh: '材料科学与工程', en: 'Materials Science and Engineering',
    degree: 'BSc · 3 年', alevel: 'AAB', ib: '35（HL 6,6,5、数学仅 AA）', test: '',
    alevelNote: '数学 / 物理 / 化学 中须有两门', offer: 'typical',
    note: '不考 A-level 数学者须 GCSE/IGCSE 数学 7/A；另有 MEng 4 年；UCAS J500',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/09894/bsc-materials-science-and-engineering/' },

  { school: 'manchester', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '数学必修', offer: 'typical', note: 'BAEcon Economics 为 AAA 且数学非强制',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/10224/bsc-economics/' },

  { school: 'manchester', dirs: ['econ'], zh: '会计与金融（BAEcon）', en: 'Accounting and Finance',
    degree: 'BAEcon · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '认可科目至少 1 门（修 2 门优先）', offer: 'typical', note: '商学院旗舰',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/05151/baecon-accounting-and-finance/' },

  { school: 'manchester', dirs: ['econ'], zh: '会计学', en: 'Accounting',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '有优先科目清单（会计/商务/经济/法律/数学等）', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/07808/bsc-accounting/' },

  { school: 'manchester', dirs: ['econ'], zh: '管理学', en: 'Management',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03519/bsc-management/' },

  { school: 'manchester', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '37（HL 7,6,6、数学 AA 7）', test: '',
    alevelNote: '数学 A* + CS/高数/生物/化学/物理之一', offer: 'typical', note: '2027 已从 2026 的 A*A*A/IB38 下调',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00560/bsc-computer-science/' },

  { school: 'manchester', dirs: ['cs', 'econ'], zh: '数据科学与经济学（BAEcon，社科院）', en: 'Data Science and Economics',
    degree: 'BAEcon · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '认可科目 ≥1', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/21873/baecon-data-science-and-economics/' },

  { school: 'manchester', dirs: ['stats'], zh: '数学与统计', en: 'Mathematics and Statistics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '37（HL 7,6,6、数学 7 仅 AA）', test: '',
    alevelNote: '数学或高数 A*', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/07101/bsc-mathematics-and-statistics/' },

  { school: 'manchester', dirs: ['stats'], zh: '数学', en: 'Mathematics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '37（HL 7,6,6、数学 7 仅 AA）', test: '',
    alevelNote: '数学或高数 A*', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00590/bsc-mathematics/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '社会学',
    en: 'BSocSc Sociology',
    degree: 'BSocSc · 3 或 4 年',
    alevel: 'ABB',
    ib: '34（HL 6,5,5）',
    alevelNote: '须含至少一门指定科目（社会学/政治/经济与社会科学史/数学/人类学/哲学/心理/历史/地理等），偏好两门；不接受通识/批判性思维',
    test: '',
    offer: 'typical',
    note: 'UCAS L300；BASS 体系可选 4 年（含海外/实习）',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00678/bsocsc-sociology/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '犯罪学',
    en: 'BA Criminology',
    degree: 'BA · 3 或 4 年',
    alevel: 'AAB（或 ABB + EPQ 达 C）',
    ib: '35（HL 6,6,5）',
    alevelNote: '不接受两门 AS 替代一门 A-level；须含法律/政治/社会学/心理/历史等指定科目之一',
    test: '',
    offer: 'typical',
    note: 'UCAS M901',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/21803/ba-criminology/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '政治与国际关系',
    en: 'BSocSc Politics and International Relations',
    degree: 'BSocSc · 3 或 4 年',
    alevel: 'AAA',
    ib: '36（HL 6,6,6）',
    alevelNote: '须含至少一门指定科目（政府与政治/经济/历史/社会学/哲学/地理等），偏好两门此类科目',
    test: '',
    offer: 'typical',
    note: 'UCAS L200；政治系单荣誉主课',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00675/bsocsc-politics-and-international-relations/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '法律',
    en: 'LLB Law',
    degree: 'LLB · 3 年',
    alevel: 'A*AA',
    ib: '37（HL 7,6,6）',
    alevelNote: '须含至少一门指定科目（法律/经济/历史/政治/哲学/数学等），偏好两门；接受 WJEC 犯罪学应用文凭（须另两门 A-level，含一门 A*）',
    test: '',
    offer: 'typical',
    note: 'UCAS M100；课程页英语项仅列 IELTS，未列 TOEFL/IGCSE-ESL',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/12446/llb-law/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '心理学',
    en: 'BSc Psychology',
    degree: 'BSc · 3 年（4 年含实习/海外）',
    alevel: 'AAA（含指定科目）',
    ib: '36（HL 6,6,6，含指定科目）',
    alevelNote: '须含心理学/生物/人类生物学/化学/物理/统计/数学/进阶数学之一；不接受艺术/设计/音乐/戏剧等表现型科目；数学与进阶数学、生物与人类生物学不可同时计入',
    test: '',
    offer: 'typical',
    note: 'UCAS C800；BPS 认证，毕业可获 Graduate Membership',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00653/bsc-psychology/' },

  { school: 'manchester',
    dirs: ['edu'],
    zh: '教育学',
    en: 'BSc Education',
    degree: 'BSc · 3 年',
    alevel: 'ABB',
    ib: '34（HL 6,5,5）',
    alevelNote: '无指定科目；须提供三门完整 A-level 且同次考试；理科 A-level 须通过实践环节',
    test: '',
    offer: 'typical',
    note: 'UCAS X300；曼大教育学院本科为 BSc Education（无 BA Education），设 Primary/Early Years、International、Special Needs 等方向',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/12384/bsc-education/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '社会人类学',
    en: 'BSocSc Social Anthropology',
    degree: 'BSocSc · 3 或 4 年',
    alevel: 'ABB',
    ib: '34（HL 6,5,5）',
    alevelNote: '须含至少一门指定科目（人类学/社会学/政治/历史/地理/哲学等），偏好两门此类科目',
    test: '',
    offer: 'typical',
    note: 'UCAS L600',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00676/bsocsc-social-anthropology/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '法律与犯罪学',
    en: 'LLB Law with Criminology',
    degree: 'LLB · 3 年',
    alevel: 'A*AA',
    ib: '37（HL 7,6,6）',
    alevelNote: '须含至少一门指定科目（法律/政治/社会学/心理等）；接受 WJEC 犯罪学三级文凭（须另两门 A-level 含一门 A*）',
    test: '',
    offer: 'typical',
    note: 'UCAS M1M9；面向刑事司法方向',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/18870/llb-law-with-criminology/' },

  { school: 'manchester',
    dirs: ['media'],
    zh: '数字媒体、文化与社会',
    en: 'Digital Media, Culture and Society BA',
    degree: 'BA · 3 年（可选 1 年实习，共 4 年）',
    alevel: 'AAB',
    ib: '35（HL665）',
    alevelNote: 'A-level 须包含一门论文类（essay-based）学科；contextual BBB；UK refugee/care-experienced BBC。GCSE/iGCSE：English Language 及 Mathematics 至少 C/4（体现读写与计算能力）',
    test: '',
    offer: 'typical',
    note: 'UCAS P390；以媒体研究为主，结合数字技能与文化、社会分析；可选 1 年行业实习（4 年制）',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/21197/ba-digital-media-culture-and-society/' },

  { school: 'manchester',
    dirs: ['media'],
    zh: '电影研究与历史学',
    en: 'Film Studies and History BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '35（HL665）',
    alevelNote: 'A-level 须含 History 且达 A；contextual ABC；UK refugee/care-experienced ACC；IB 须含特定 HL 科目。GCSE/iGCSE：English Language 及 Mathematics 至少 C/4',
    test: '',
    offer: 'typical',
    note: 'UCAS PV10；与历史学联合荣誉；电影以史论与批评为主（非制作）；曼大电影研究均以联合荣誉形式开设，另可搭配 History of Art / East Asian Studies / Middle Eastern Studies 等',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/11793/ba-film-studies-and-history/' },




  // ═══════════ 爱丁堡 Edinburgh（分数=近年获 offer 区间 from–to；苏格兰一般 4 年；经管为 MA(Hons) 本科） ═══════════
  { school: 'edinburgh', dirs: ['bio'], zh: '生物科学（生化方向）', en: 'Biological Sciences (Biochemistry)',
    degree: 'BSc (Hons) · 4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '生物 B、化学 B，并有一科 A', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/13-biological-sciences-biochemistry' },

  { school: 'edinburgh', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'BSc (Hons) · 3–4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '化学 B + 数学 B', offer: 'range', note: '可直入大二 3 年读完',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/21-chemistry' },

  { school: 'edinburgh', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc (Hons) · 4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '数学 A + 物理 B', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/33-physics' },

  { school: 'edinburgh', dirs: ['eng'], zh: '电子与电气工程', en: 'Electronics and Electrical Engineering',
    degree: 'BEng (Hons) · 3–4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '数学 B + 相关理科 B', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/88-electronics-and-electrical-engineering' },

  { school: 'edinburgh', dirs: ['eng'], zh: '机械工程', en: 'Mechanical Engineering',
    degree: 'BEng (Hons) · 3–4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '数学至少 B + 科学类 B（首选物理）', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/82-mechanical-engineering' },

  { school: 'edinburgh', dirs: ['eng'], zh: '化学工程', en: 'Chemical Engineering',
    degree: 'BEng (Hons) · 3–4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '数学 B + 化学 B', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/99-chemical-engineering' },

  { school: 'edinburgh', dirs: ['eng'], zh: '土木工程', en: 'Civil Engineering',
    degree: 'BEng (Hons) · 3–4 年', alevel: 'ABB–BBB', ib: '34（HL655）–32（HL555）', test: '',
    alevelNote: '数学 B + 科学类 B', offer: 'range', note: '土木门槛明显低于其他工程',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/76-civil-engineering' },

  { school: 'edinburgh', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'MA (Hons) · 4 年', alevel: 'A*A*A*–A*AA', ib: '40（HL766）–37（HL666）', test: '',
    alevelNote: '数学 B 或 AS 数学 A', offer: 'range', note: '竞争极高，分差上限全 A*；MA=本科荣誉学位',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/122-economics' },

  { school: 'edinburgh', dirs: ['econ'], zh: '会计与金融', en: 'Accounting and Finance',
    degree: 'MA (Hons) · 4 年', alevel: 'A*AA–AAA', ib: '40（HL766）–37（HL666）', test: '',
    alevelNote: '无必修 A-level（GCSE 数学 B/6）', offer: 'range', note: '商学院极热门',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/464-accounting-and-finance' },

  { school: 'edinburgh', dirs: ['econ'], zh: '商业管理', en: 'Business Management',
    degree: 'MA (Hons) · 4 年', alevel: 'A*AA–AAA', ib: '40（HL766）–37（HL666）', test: '',
    alevelNote: 'GCSE 数学 B/6', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/182-business-management' },

  { school: 'edinburgh', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc (Hons) · 4 年', alevel: 'A*A*A*–AAB', ib: '43（HL777）–34（HL665）', test: '',
    alevelNote: '数学 A，须入学前 2 年内取得', offer: 'range', note: '信息学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/57-computer-science' },

  { school: 'edinburgh', dirs: ['stats'], zh: '数学与统计', en: 'Mathematics and Statistics',
    degree: 'BSc (Hons) · 4 年', alevel: 'A*A*A*–A*AB', ib: '38（HL766）–34（HL765）', test: '',
    alevelNote: '数学 A*；建议高数', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/63-mathematics-and-statistics' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '社会学',
    en: 'Sociology MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'AAA–AAB',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L300；社会与政治科学学院（School of Social and Political Science）；可选计量方法（Quantitative Methods）方向',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/125-sociology' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '政治学',
    en: 'Politics MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*A*A*–AAA',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L200；社会与政治科学学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/124-politics' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '社会人类学',
    en: 'Social Anthropology MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'AAA–AAB',
    ib: '36（HL665）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L600；社会与政治科学学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/128-social-anthropology' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '国际关系',
    en: 'International Relations MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*A*A*–AAA',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L250；社会与政治科学学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/377-international-relations' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '法律',
    en: 'Law LLB (Hons)',
    degree: 'LLB (Hons) · 4 年',
    alevel: 'A*A*A–A*AA',
    ib: '40（HL766）–37（HL666）',
    alevelNote: 'A-level 英语（English Literature / English Language / 合并 English）B；GCSE English Language 与 English Literature 均 A/7 可替代 A-level 英语',
    test: '',
    offer: 'range',
    note: 'UCAS M114；爱丁堡法学院（Edinburgh Law School）；4 年制苏格兰法学士（LLB）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/168-law-ordinary-and-honours' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '心理学',
    en: 'Psychology BSc (Hons)',
    degree: 'BSc (Hons) · 4 年',
    alevel: 'A*A*A*–AAA',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '须含生物/化学/计算机/环境科学/地理/地质/数学/物理/心理等指定科目之一 B；GCSE 英语 C/4，GCSE 数学 A/7（或数学+物理 B/6，或数学+双科学 B/6）；IB 补数学 SL 6（若 HL 无数学）',
    test: '',
    offer: 'range',
    note: 'UCAS C802；哲学、心理学与语言科学学院（PPLS）；BPS 认证',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/370-psychology' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '社会政策与社会学',
    en: 'Social Policy and Sociology MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*AA–AAB',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS LL43；社会与政治科学学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/141-social-policy-and-sociology' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '哲学',
    en: 'Philosophy MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*AA–AAB',
    ib: '36（HL665）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS V500；哲学、心理学与语言科学学院（PPLS）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/311-philosophy' },

  { school: 'edinburgh',
    dirs: ['edu'],
    zh: '体育教育',
    en: 'Physical Education MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语语言 C/4、英语文学 C/4、数学 C/4；IB 补数学 SL 4',
    test: '',
    offer: 'range',
    note: 'UCAS XC61；Moray House 教育与体育学院；每学年含中小学体育教学实习（必修），须加入 Disclosure Scotland PVG 背景审查',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/352-physical-education' },

  { school: 'edinburgh',
    dirs: ['edu'],
    zh: '小学教育（盖尔语方向）',
    en: 'Primary Education with Gaelic (Learners) MA (Hons)',
    degree: 'MA (Hons) · 5 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语语言 C/4、英语文学 C/4、数学 C/4，另需英语以外的一门语言 B/6；IB 补数学 SL 4、外语 SL 5',
    test: '',
    offer: 'range',
    note: 'UCAS 3R67；Moray House 教育与体育学院；5 年制，培养以盖尔语与英语授课的小学教师，含中小学教学实习（必修），须加入 Disclosure Scotland PVG 背景审查',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/629-primary-education-with-gaelic-learners' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '英国文学',
    en: 'English Literature MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*A*A*–A*AA',
    ib: '40（HL766）–37（HL666）',
    alevelNote: 'A-level 英语文学或合并 English B；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS Q306；文学、语言与文化学院（School of Literatures, Languages and Cultures）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/197-english-literature' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '历史学',
    en: 'History MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*A*A–AAB',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS V100；历史、古典与考古学院（School of History, Classics and Archaeology）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/301-history' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '语言学',
    en: 'Linguistics MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS Q100；哲学、心理学与语言科学学院（PPLS）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/194-linguistics' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '地理学（人文地理）',
    en: 'Geography MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*AA–ABB',
    ib: '38（HL766）–32（HL655）',
    alevelNote: '无指定 A-level 科目（地理优先）；GCSE 数学 C/4、英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L700；地球科学学院（School of GeoSciences）；MA 走社会科学 / 人文路径，侧重人文地理',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/130-geography' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '地理学（自然地理）',
    en: 'Geography BSc (Hons)',
    degree: 'BSc (Hons) · 4 年',
    alevel: 'AAA–ABB',
    ib: '34（HL655）–32（HL655）',
    alevelNote: '须含地理 / 生物 / 化学 / 电子 / 环境科学 / 环境技术 / 地质 / 数学 / 物理中任两门 B；GCSE 数学 B/6、英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS F800；地球科学学院（School of GeoSciences）；BSc 走自然科学路径，侧重自然地理',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/50-geography' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '健康社会科学',
    en: 'Health in Social Science MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS 2D50；健康社会科学学院（School of Health in Social Science）；跨健康、社会与政策的交叉学科',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/627-health-in-social-science' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '社会工作',
    en: 'Social Work BSc (Hons)',
    degree: 'BSc (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4、数学 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L500；社会与政治科学学院（School of Social and Political Science）；含必修实习，须符合 SSSC 的 fitness to practise 要求并满足实习疫苗接种要求',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/127-social-work' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '艺术史',
    en: 'History of Art MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS V350；爱丁堡艺术学院（Edinburgh College of Art）',
    qs: ['art-design'],
    url: 'https://study.ed.ac.uk/programmes/undergraduate/307-history-of-art' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '音乐',
    en: 'Music BMus (Hons)',
    degree: 'BMus (Hons) · 4 年',
    alevel: 'AAB–ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS W302；爱丁堡艺术学院（Edinburgh College of Art，含 Reid School of Music）；不设面试，但须展现对音乐的投入；除 Advanced Higher / A-level Music 达 A 或 IB HL Music 6 外，须修 Fundamentals of Music Theory 课程',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/347-music' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '神学',
    en: 'Theology MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS QVV6；神学院（School of Divinity，New College）',
    qs: [],
    url: 'https://study.ed.ac.uk/programmes/undergraduate/237-theology' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '凯尔特研究',
    en: 'Celtic MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4，另需英语以外的一门语言 B/6；IB 补英语以外语言 SL 5',
    test: '',
    offer: 'range',
    note: 'UCAS Q500；文学、语言与文化学院（School of Literatures, Languages and Cultures）；凯尔特与苏格兰研究方向，可选盖尔语、威尔士语、爱尔兰语等',
    qs: ['modern-languages'],
    url: 'https://study.ed.ac.uk/programmes/undergraduate/199-celtic' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '古典学',
    en: 'Classics MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'AAA–ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS Q800；历史、古典与考古学院（School of History, Classics and Archaeology）；不要求拉丁语 / 希腊语基础，可从零起点学习古典语言',
    qs: [],
    url: 'https://study.ed.ac.uk/programmes/undergraduate/203-classics' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '古代史',
    en: 'Ancient History MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'AAA–ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS V110；历史、古典与考古学院（School of History, Classics and Archaeology）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/302-ancient-history' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '考古学',
    en: 'Archaeology MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS V400；历史、古典与考古学院（School of History, Classics and Archaeology）',
    qs: [],
    url: 'https://study.ed.ac.uk/programmes/undergraduate/310-archaeology' },

  { school: 'edinburgh',
    dirs: ['media'],
    zh: '电影与电视',
    en: 'Film and Television BA (Hons)',
    degree: 'BA (Hons) · 3–4 年',
    alevel: 'ABB',
    ib: '34（HL 655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4；IB 另须 SL 英语 5。以近年实际发放 offer 公布（standard 与 widening access 均为 ABB / 34）',
    test: '',
    offer: 'range',
    note: '爱丁堡艺术学院（ECA）开设；须提交数字作品集（≤5 分钟短片或片段 + 3 道书面问答）；以导演、编剧、摄影、剪辑、声音等制作为主',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/497-film-and-television' },




  // ═══════════ 华威 Warwick（2027 官方页） ═══════════
  { school: 'warwick', dirs: ['bio'], zh: '生物医学', en: 'Biomedical Sciences',
    degree: 'BSc · 3 年', alevel: 'AAB / AAA', ib: '34 / 36', test: '',
    alevelNote: 'AAB 含生物+第二门科学；或 AAA 含生物', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-biomedical-sciences/' },

  { school: 'warwick', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAB / AAA', ib: '34 / 36', test: '',
    alevelNote: 'AAB 含生物+化学；或 AAA 含化学+数学/物理/统计并补生物', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-biochemistry/' },

  { school: 'warwick', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'BSc · 3 年', alevel: 'AAB', ib: '34（HL 化学 6 + 第二门理科 5）', test: '',
    alevelNote: '化学 + 数学/高数/物理/生物等之一', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-chemistry/' },

  { school: 'warwick', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 AA 6 + 物理 6）', test: '',
    alevelNote: '数学或高数 + 物理 A', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-physics/' },

  { school: 'warwick', dirs: ['eng'], zh: '工程（通用，大一通识）', en: 'Engineering',
    degree: 'BEng · 3 年', alevel: 'AAA', ib: '36（数学+物理 6,6）', test: '',
    alevelNote: '数学与物理（强 profile 可只含其一）', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/beng-engineering/' },

  { school: 'warwick', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 6）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: 'TMUA 高分可降至 AAA',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-economics/' },

  { school: 'warwick', dirs: ['econ'], zh: '会计与金融', en: 'Accounting and Finance',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 6）', test: '',
    alevelNote: '数学 A；GCSE 英语 6/B', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-accounting-finance/' },

  { school: 'warwick', dirs: ['econ'], zh: '商务与管理', en: 'Business and Management',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38', test: '',
    alevelNote: 'GCSE 数学 7/A + 英语 6/B', offer: 'typical', note: '2026 名 Management，2027 起更名',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-business-management/' },

  { school: 'warwick', dirs: ['econ'], zh: '国际商务与管理（4 年含海外）', en: 'International Business and Management',
    degree: 'BSc · 4 年', alevel: 'A*AA', ib: '38', test: '',
    alevelNote: 'GCSE 数学 7/A + 英语 6/B', offer: 'typical', note: '第三年海外/实习',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-international-business-management/' },

  { school: 'warwick', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 7）', test: '',
    alevelNote: '数学 A*；只取前三门成绩', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-computer-science/' },

  { school: 'warwick', dirs: ['cs', 'stats'], zh: '数据科学（统计系）', en: 'Data Science',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 7）', test: '',
    alevelNote: '数学+高数 A*A，或 A*AA + STEP2/TMUA5.0/AEA；不读高数则 A*A*A*', offer: 'typical', note: '2023 新开热门；可叠加 STEP/TMUA 替代路径',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-data-science/' },

  { school: 'warwick', dirs: ['stats'], zh: 'MORSE（数学-运筹-统计-经济）', en: 'MORSE',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 7）', test: '',
    alevelNote: '有高数者：A*A*A 含数学+高数 A*A；无高数者 A*A*A*', offer: 'typical', note: '统计系旗舰；可 +STEP2/TMUA5.0/AEA 替代',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-morse/' },

  { school: 'warwick', dirs: ['stats'], zh: '数学', en: 'Mathematics',
    degree: 'BSc · 3 年', alevel: 'A*A* + A', ib: '39（3HL 数学 AA 6）', test: '',
    alevelNote: '数学+高数均 A*', offer: 'typical', note: '普遍要求 TMUA，未达标 offer 加 STEP grade 2',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-mathematics/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '社会学',
    en: 'Sociology BA',
    degree: 'BA · 3 年',
    alevel: 'ABB',
    ib: '32',
    alevelNote: '无指定 A-level 科目；另需 GCSE English Language 6/B（或 GCSE English Literature 6/B + English Language 4/C）',
    test: '',
    offer: 'typical',
    note: 'UCAS L300；Band B 课程',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-sociology/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '政治学',
    en: 'Politics BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36',
    alevelNote: '无指定 A-level 科目',
    test: '',
    offer: 'typical',
    note: 'UCAS L200；由 PAIS（政治与国际研究系）开设',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-politics/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '政治与国际研究',
    en: 'Politics and International Studies BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36',
    alevelNote: '无指定 A-level 科目',
    test: '',
    offer: 'typical',
    note: 'UCAS L260；华威国际关系方向由 PAIS 系开设（无独立 BA International Relations）',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-politics-international-studies/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '法律',
    en: 'Law LLB',
    degree: 'LLB · 3 年',
    alevel: 'A*AA',
    ib: '38',
    alevelNote: '无指定 A-level 科目；需 GCSE 数学 4/C；多数 GCSE 科目需 7(A)/8-9(A*)；不建议 Law+Sociology+Psychology 三科重合组合',
    test: '',
    offer: 'typical',
    note: 'UCAS M100；不要求 LNAT；Band C 课程',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/llb-law/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '心理学',
    en: 'Psychology BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '34',
    alevelNote: 'AAB 须含一门科学（数学/进阶数学/统计/化学/生物/人体生物学/物理）；若不修科学则 AAA/A*AB；需 GCSE 数学/统计 6/B',
    test: '',
    offer: 'typical',
    note: 'BPS 认证；IB 34（含 HL 科学）或 36（无 HL 科学）',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-psychology/' },

  { school: 'warwick',
    dirs: ['edu'],
    zh: '教育学',
    en: 'Education BA',
    degree: 'BA · 3 年',
    alevel: 'ABB',
    ib: '32',
    alevelNote: '无指定 A-level 科目；另需 GCSE English Language 6/B',
    test: '',
    offer: 'typical',
    note: 'UCAS X35B；华威教育学院（Education Studies）开设',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-education/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '哲学',
    en: 'Philosophy BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36',
    alevelNote: '无指定 A-level 科目',
    test: '',
    offer: 'typical',
    note: 'UCAS V500；哲学系开设',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-philosophy/' },

  { school: 'warwick',
    dirs: ['media'],
    zh: '媒体与创意产业',
    en: 'Media and Creative Industries BA',
    degree: 'BA · 3 年',
    alevel: 'AAB',
    ib: '34',
    alevelNote: '无指定科目；contextual BBB。GCSE：English Language 4/C 及数学或科学一门 4/C',
    test: '',
    offer: 'typical',
    note: 'UCAS P301；Centre for Cultural and Media Policy Studies 开设；达要求者需提交作品集（创意作品 + 视频 + 书面回答）；含 Media Lab 与行业实习/驻留',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-media-creative/' },

  { school: 'warwick',
    dirs: ['media'],
    zh: '电影研究',
    en: 'Film Studies BA',
    degree: 'BA · 3 年',
    alevel: 'ABB',
    ib: '32',
    alevelNote: '须含以下科目之一：Classical Civilisation、Drama and Theatre、English Language-Literature (combined)、English Language、English Literature、Film Studies、History、Media Studies、Philosophy、Politics、Religious Studies、Sociology；IB 须含以下 HL 之一：English Language-Literature、English Literature、Literature and Performance、Film、Global Politics、History、Philosophy、Social and Cultural Anthropology、Theatre；contextual BBB / 30',
    test: '',
    offer: 'typical',
    note: 'UCAS W620；Film & Television Studies 系开设；偏电影批评与理论（需较强批判性写作能力）',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-film-studies/' },

  { school: 'warwick',
    dirs: ['media'],
    zh: '电影与文学',
    en: 'Film and Literature BA',
    degree: 'BA · 3 年',
    alevel: 'ABB',
    ib: '32',
    alevelNote: '须含 English Literature 或 English Language and Literature（合并）且达 A；IB 须含 HL English Literature 或 English Language and Literature 6；contextual BBB / 30',
    test: '',
    offer: 'typical',
    note: 'UCAS QW26；由 Film & Television Studies 与 English and Comparative Literary Studies 合办；可选与 London Film School 合作的电影制作模块或毕业论文',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-film-literature/' },

];

// 说明：本数据集只收录各校实际开设的课程，不标注“某校没有某专业”之类的对照信息
