// QS World University Rankings by Subject 2026（QS2026 学科排名）
// 数据来源：QS 官方 2026 学科榜（2026-03 发布），2026-09 抓取；名次含并列（形如 "=4"）与区间（形如 "51-100"）
// 收录范围：本站覆盖的 17 所大学，且只收录**前 200 名**以内（含 51-100 / 101-150 / 151-200 等区间段）
// 200 名之后的区间段（201-250、251-300…）未收录 —— 故表内“—”表示未进前 200，不代表该校完全未上榜

const QS_YEAR = 2026;

const QS_SUBJECT_ZH = {
 "accounting-finance": "会计与金融",
 "anthropology": "人类学",
 "art-design": "艺术与设计",
 "biological-sciences": "生物科学",
 "business-management-studies": "商业与管理",
 "chemical-engineering": "化学工程",
 "chemistry": "化学",
 "civil-structural-engineering": "土木与结构工程",
 "communication-media-studies": "传媒与媒体研究",
 "computer-science-information-systems": "计算机与信息系统",
 "data-science-artificial-intelligence": "数据科学与AI",
 "dentistry": "牙医",
 "economics-econometrics": "经济与计量经济",
 "education-training": "教育与培训",
 "electrical-electronic-engineering": "电子电气工程",
 "english-language-literature": "英语语言与文学",
 "environmental-sciences": "环境科学",
 "geography": "地理",
 "history": "历史",
 "hospitality-leisure-management": "酒店与休闲管理",
 "law-legal-studies": "法学",
 "linguistics": "语言学",
 "mathematics": "数学",
 "mechanical-aeronautical-manufacturing-engineering": "机械/航空/制造工程",
 "medicine": "医学",
 "modern-languages": "现代语言",
 "nursing": "护理",
 "performing-arts": "表演艺术",
 "pharmacy-pharmacology": "药学与药理",
 "philosophy": "哲学",
 "physics-astronomy": "物理与天文",
 "politics": "政治学",
 "psychology": "心理学",
 "social-policy-administration": "社会政策与行政",
 "sociology": "社会学",
 "sports-related-subjects": "体育相关学科",
 "statistics-operational-research": "统计与运筹"
};

const QS_DIR_SUBJECTS = {
 "bio": [
  "biological-sciences",
  "chemistry",
  "medicine",
  "pharmacy-pharmacology",
  "dentistry",
  "nursing"
 ],
 "physics": [
  "physics-astronomy"
 ],
 "eng": [
  "mechanical-aeronautical-manufacturing-engineering",
  "electrical-electronic-engineering",
  "civil-structural-engineering",
  "chemical-engineering"
 ],
 "econ": [
  "economics-econometrics",
  "business-management-studies",
  "accounting-finance"
 ],
 "cs": [
  "computer-science-information-systems",
  "data-science-artificial-intelligence"
 ],
 "stats": [
  "mathematics",
  "statistics-operational-research"
 ],
 "edu": [
  "education-training"
 ],
 "arts": [
  "history",
  "english-language-literature",
  "modern-languages",
  "linguistics",
  "philosophy",
  "performing-arts"
 ],
 "social": [
  "anthropology",
  "social-policy-administration",
  "law-legal-studies",
  "psychology",
  "geography",
  "sociology",
  "politics"
 ],
 "media": [
  "communication-media-studies"
 ]
};

const QS_RANKS = {
 "oxford": {
  "accounting-finance": "4",
  "anthropology": "1",
  "art-design": "17",
  "biological-sciences": "3",
  "business-management-studies": "5",
  "chemical-engineering": "9",
  "chemistry": "5",
  "civil-structural-engineering": "12",
  "computer-science-information-systems": "=4",
  "data-science-artificial-intelligence": "=6",
  "economics-econometrics": "8",
  "education-training": "=3",
  "electrical-electronic-engineering": "7",
  "english-language-literature": "2",
  "environmental-sciences": "=2",
  "geography": "1",
  "history": "2",
  "law-legal-studies": "2",
  "linguistics": "4",
  "mathematics": "2",
  "mechanical-aeronautical-manufacturing-engineering": "=7",
  "medicine": "2",
  "modern-languages": "1",
  "performing-arts": "18",
  "pharmacy-pharmacology": "=3",
  "philosophy": "3",
  "physics-astronomy": "3",
  "politics": "2",
  "psychology": "=3",
  "social-policy-administration": "2",
  "sociology": "2",
  "statistics-operational-research": "5"
 },
 "cambridge": {
  "accounting-finance": "7",
  "anthropology": "3",
  "art-design": "=43",
  "biological-sciences": "5",
  "business-management-studies": "6",
  "chemical-engineering": "5",
  "chemistry": "=2",
  "civil-structural-engineering": "=9",
  "communication-media-studies": "12",
  "computer-science-information-systems": "8",
  "data-science-artificial-intelligence": "9",
  "economics-econometrics": "10",
  "education-training": "6",
  "electrical-electronic-engineering": "6",
  "english-language-literature": "1",
  "environmental-sciences": "6",
  "geography": "3",
  "history": "3",
  "law-legal-studies": "3",
  "linguistics": "3",
  "mathematics": "3",
  "mechanical-aeronautical-manufacturing-engineering": "4",
  "medicine": "5",
  "modern-languages": "2",
  "performing-arts": "23",
  "pharmacy-pharmacology": "7",
  "philosophy": "7",
  "physics-astronomy": "5",
  "politics": "7",
  "psychology": "2",
  "social-policy-administration": "6",
  "sociology": "7",
  "statistics-operational-research": "6"
 },
 "lse": {
  "accounting-finance": "8",
  "anthropology": "8",
  "business-management-studies": "11",
  "communication-media-studies": "6",
  "data-science-artificial-intelligence": "51-100",
  "economics-econometrics": "6",
  "geography": "2",
  "history": "10",
  "law-legal-studies": "9",
  "mathematics": "108",
  "modern-languages": "101-150",
  "philosophy": "8",
  "politics": "5",
  "psychology": "19",
  "social-policy-administration": "4",
  "sociology": "6",
  "statistics-operational-research": "45"
 },
 "imperial": {
  "accounting-finance": "=15",
  "art-design": "=62",
  "biological-sciences": "=7",
  "business-management-studies": "=22",
  "chemical-engineering": "4",
  "chemistry": "10",
  "civil-structural-engineering": "7",
  "computer-science-information-systems": "12",
  "data-science-artificial-intelligence": "=15",
  "economics-econometrics": "29",
  "electrical-electronic-engineering": "9",
  "environmental-sciences": "11",
  "hospitality-leisure-management": "101-150",
  "mathematics": "=8",
  "mechanical-aeronautical-manufacturing-engineering": "=9",
  "medicine": "7",
  "pharmacy-pharmacology": "10",
  "physics-astronomy": "12",
  "statistics-operational-research": "10"
 },
 "manchester": {
  "accounting-finance": "21",
  "anthropology": "20",
  "biological-sciences": "48",
  "business-management-studies": "41",
  "chemical-engineering": "=17",
  "chemistry": "23",
  "civil-structural-engineering": "51-100",
  "communication-media-studies": "51-100",
  "computer-science-information-systems": "=58",
  "data-science-artificial-intelligence": "51-100",
  "dentistry": "48",
  "economics-econometrics": "68",
  "education-training": "35",
  "electrical-electronic-engineering": "34",
  "english-language-literature": "=22",
  "environmental-sciences": "=45",
  "geography": "9",
  "history": "39",
  "law-legal-studies": "70",
  "linguistics": "34",
  "mathematics": "54",
  "mechanical-aeronautical-manufacturing-engineering": "27",
  "medicine": "=26",
  "modern-languages": "28",
  "nursing": "=10",
  "performing-arts": "51-100",
  "pharmacy-pharmacology": "18",
  "physics-astronomy": "=34",
  "politics": "=53",
  "psychology": "=49",
  "social-policy-administration": "=42",
  "sociology": "20",
  "statistics-operational-research": "51-100"
 },
 "hku": {
  "accounting-finance": "26",
  "anthropology": "51-100",
  "art-design": "56",
  "biological-sciences": "51",
  "business-management-studies": "=32",
  "chemical-engineering": "64",
  "chemistry": "45",
  "civil-structural-engineering": "=20",
  "communication-media-studies": "51-100",
  "computer-science-information-systems": "=27",
  "data-science-artificial-intelligence": "18",
  "dentistry": "2",
  "economics-econometrics": "=31",
  "education-training": "5",
  "electrical-electronic-engineering": "51",
  "english-language-literature": "=22",
  "environmental-sciences": "=47",
  "geography": "11",
  "history": "28",
  "hospitality-leisure-management": "36",
  "law-legal-studies": "20",
  "linguistics": "=27",
  "mathematics": "51",
  "mechanical-aeronautical-manufacturing-engineering": "49",
  "medicine": "=37",
  "modern-languages": "23",
  "nursing": "=30",
  "performing-arts": "51-100",
  "pharmacy-pharmacology": "60",
  "philosophy": "101-150",
  "physics-astronomy": "63",
  "politics": "=53",
  "psychology": "35",
  "social-policy-administration": "32",
  "sociology": "24",
  "sports-related-subjects": "51-100",
  "statistics-operational-research": "32"
 },
 "hkust": {
  "accounting-finance": "33",
  "biological-sciences": "=156",
  "business-management-studies": "30",
  "chemical-engineering": "70",
  "chemistry": "52",
  "civil-structural-engineering": "27",
  "computer-science-information-systems": "33",
  "data-science-artificial-intelligence": "25",
  "economics-econometrics": "37",
  "electrical-electronic-engineering": "33",
  "environmental-sciences": "80",
  "mathematics": "=56",
  "mechanical-aeronautical-manufacturing-engineering": "41",
  "physics-astronomy": "83",
  "statistics-operational-research": "31"
 },
 "cuhk": {
  "accounting-finance": "34",
  "anthropology": "49",
  "art-design": "151-200",
  "biological-sciences": "110",
  "business-management-studies": "53",
  "chemical-engineering": "151-200",
  "chemistry": "=98",
  "civil-structural-engineering": "101-150",
  "communication-media-studies": "16",
  "computer-science-information-systems": "37",
  "data-science-artificial-intelligence": "28",
  "economics-econometrics": "44",
  "education-training": "24",
  "electrical-electronic-engineering": "82",
  "english-language-literature": "56",
  "environmental-sciences": "151-200",
  "geography": "21",
  "history": "51-100",
  "hospitality-leisure-management": "=42",
  "law-legal-studies": "53",
  "linguistics": "25",
  "mathematics": "41",
  "mechanical-aeronautical-manufacturing-engineering": "=93",
  "medicine": "=37",
  "modern-languages": "=49",
  "nursing": "=6",
  "performing-arts": "101-150",
  "pharmacy-pharmacology": "=72",
  "philosophy": "51-100",
  "physics-astronomy": "=131",
  "politics": "101-150",
  "psychology": "=43",
  "social-policy-administration": "51-100",
  "sociology": "30",
  "sports-related-subjects": "=31",
  "statistics-operational-research": "51-100"
 },
 "warwick": {
  "accounting-finance": "=39",
  "biological-sciences": "=161",
  "business-management-studies": "35",
  "chemistry": "=126",
  "communication-media-studies": "51-100",
  "computer-science-information-systems": "84",
  "data-science-artificial-intelligence": "51-100",
  "economics-econometrics": "25",
  "education-training": "151-200",
  "electrical-electronic-engineering": "=139",
  "english-language-literature": "27",
  "history": "=47",
  "law-legal-studies": "=84",
  "linguistics": "151-200",
  "mathematics": "28",
  "mechanical-aeronautical-manufacturing-engineering": "=125",
  "medicine": "167",
  "modern-languages": "62",
  "performing-arts": "51-100",
  "philosophy": "38",
  "physics-astronomy": "=137",
  "politics": "49",
  "psychology": "=72",
  "social-policy-administration": "101-150",
  "sociology": "61",
  "statistics-operational-research": "=27"
 },
 "edinburgh": {
  "accounting-finance": "42",
  "anthropology": "=17",
  "art-design": "=89",
  "biological-sciences": "19",
  "business-management-studies": "=109",
  "chemical-engineering": "=65",
  "chemistry": "=58",
  "civil-structural-engineering": "51-100",
  "communication-media-studies": "36",
  "computer-science-information-systems": "=22",
  "data-science-artificial-intelligence": "30",
  "economics-econometrics": "=80",
  "education-training": "9",
  "electrical-electronic-engineering": "=61",
  "english-language-literature": "6",
  "environmental-sciences": "=43",
  "geography": "19",
  "history": "22",
  "law-legal-studies": "15",
  "linguistics": "11",
  "mathematics": "=29",
  "mechanical-aeronautical-manufacturing-engineering": "=87",
  "medicine": "22",
  "modern-languages": "12",
  "nursing": "44",
  "performing-arts": "101-150",
  "pharmacy-pharmacology": "39",
  "philosophy": "24",
  "physics-astronomy": "42",
  "politics": "27",
  "psychology": "23",
  "social-policy-administration": "10",
  "sociology": "28",
  "sports-related-subjects": "20",
  "statistics-operational-research": "=33"
 },
 "ucl": {
  "accounting-finance": "44",
  "anthropology": "=4",
  "art-design": "58",
  "biological-sciences": "=9",
  "business-management-studies": "68",
  "chemical-engineering": "=17",
  "chemistry": "24",
  "civil-structural-engineering": "=25",
  "communication-media-studies": "35",
  "computer-science-information-systems": "20",
  "data-science-artificial-intelligence": "22",
  "dentistry": "37",
  "economics-econometrics": "17",
  "education-training": "1",
  "electrical-electronic-engineering": "39",
  "english-language-literature": "12",
  "environmental-sciences": "=23",
  "geography": "5",
  "history": "20",
  "law-legal-studies": "=13",
  "linguistics": "=13",
  "mathematics": "=42",
  "mechanical-aeronautical-manufacturing-engineering": "=57",
  "medicine": "6",
  "modern-languages": "13",
  "pharmacy-pharmacology": "=3",
  "philosophy": "51-100",
  "physics-astronomy": "25",
  "politics": "20",
  "psychology": "5",
  "social-policy-administration": "=26",
  "sociology": "31",
  "sports-related-subjects": "35",
  "statistics-operational-research": "22"
 },
 "polyu": {
  "accounting-finance": "51",
  "art-design": "24",
  "business-management-studies": "52",
  "chemical-engineering": "151-200",
  "chemistry": "=167",
  "civil-structural-engineering": "18",
  "communication-media-studies": "151-200",
  "computer-science-information-systems": "70",
  "data-science-artificial-intelligence": "51-100",
  "economics-econometrics": "=139",
  "electrical-electronic-engineering": "=73",
  "english-language-literature": "101-150",
  "environmental-sciences": "34",
  "geography": "51-100",
  "hospitality-leisure-management": "15",
  "linguistics": "45",
  "mathematics": "68",
  "mechanical-aeronautical-manufacturing-engineering": "53",
  "nursing": "18",
  "physics-astronomy": "151-200",
  "psychology": "101-150",
  "sociology": "101-150",
  "sports-related-subjects": "51-100",
  "statistics-operational-research": "=40"
 },
 "cityu": {
  "accounting-finance": "52",
  "biological-sciences": "=198",
  "business-management-studies": "=73",
  "chemistry": "=91",
  "civil-structural-engineering": "51-100",
  "communication-media-studies": "=49",
  "computer-science-information-systems": "=67",
  "data-science-artificial-intelligence": "51-100",
  "economics-econometrics": "=74",
  "electrical-electronic-engineering": "=71",
  "english-language-literature": "93",
  "environmental-sciences": "=126",
  "hospitality-leisure-management": "51-100",
  "law-legal-studies": "41",
  "linguistics": "36",
  "mathematics": "=80",
  "mechanical-aeronautical-manufacturing-engineering": "=109",
  "modern-languages": "79",
  "physics-astronomy": "144",
  "politics": "=91",
  "psychology": "151-200",
  "social-policy-administration": "=46",
  "sociology": "101-150",
  "statistics-operational-research": "101-150"
 },
 "kcl": {
  "accounting-finance": "=66",
  "biological-sciences": "=33",
  "business-management-studies": "=66",
  "chemistry": "=100",
  "communication-media-studies": "=19",
  "computer-science-information-systems": "46",
  "data-science-artificial-intelligence": "=45",
  "dentistry": "5",
  "economics-econometrics": "=119",
  "education-training": "16",
  "electrical-electronic-engineering": "=95",
  "english-language-literature": "14",
  "environmental-sciences": "151-200",
  "geography": "14",
  "history": "21",
  "law-legal-studies": "16",
  "linguistics": "101-150",
  "mathematics": "=60",
  "mechanical-aeronautical-manufacturing-engineering": "151-200",
  "medicine": "11",
  "modern-languages": "21",
  "nursing": "2",
  "performing-arts": "48",
  "pharmacy-pharmacology": "17",
  "philosophy": "=14",
  "physics-astronomy": "=81",
  "politics": "11",
  "psychology": "=15",
  "social-policy-administration": "31",
  "sociology": "44",
  "sports-related-subjects": "47",
  "statistics-operational-research": "101-150"
 },
 "hkbu": {
  "accounting-finance": "151-200",
  "communication-media-studies": "48",
  "data-science-artificial-intelligence": "101-200",
  "geography": "151-200",
  "history": "151-200",
  "linguistics": "101-150",
  "modern-languages": "101-150",
  "social-policy-administration": "101-150",
  "sociology": "101-150",
  "sports-related-subjects": "101-150"
 },
 "eduhk": {
  "education-training": "7",
  "linguistics": "151-200"
 },
 "lingnan": {
  "communication-media-studies": "151-200",
  "philosophy": "151-200"
 }
};
