// 英国九校本科录取要求速查 —— 数据（2026-09 抓取核对，面向 2027 年 9 月入学申请季）
// 方向编码：bio=生化医药化学 / physics=物理 / eng=工程 / econ=经济管理金融会计 / cs=计算机数据AI / stats=统计数学精算 / edu=教育 / social=社科传媒人文
// 成绩口径见"术语与口径说明"：典型（典型录取水平）/ 最低 / 区间；剑桥为各学院最低 offer 水平

const SCHOOLS = [
  { key: 'oxford',    zh: '牛津',   en: 'University of Oxford',  group: 'G5·牛剑', mark: '牛', color: '#7c0f28' },
  { key: 'cambridge', zh: '剑桥',   en: 'University of Cambridge', group: 'G5·牛剑', mark: '剑', color: '#0f4c81' },
  { key: 'imperial',  zh: '帝国理工', en: 'Imperial College London', group: 'G5', mark: '帝', color: '#162d5c' },
  { key: 'lse',       zh: 'LSE',    en: 'London School of Economics', group: 'G5', mark: 'LSE', color: '#a61c5b' },
  { key: 'ucl',       zh: 'UCL',    en: 'University College London', group: 'G5', mark: 'UCL', color: '#511c5c' },
  { key: 'kcl',       zh: 'KCL',    en: "King's College London", group: '王爱曼华', mark: 'KCL', color: '#3a5da8' },
  { key: 'manchester',zh: '曼大',   en: 'University of Manchester', group: '王爱曼华', mark: '曼', color: '#73172d' },
  { key: 'edinburgh', zh: '爱丁堡', en: 'University of Edinburgh', group: '王爱曼华', mark: '爱', color: '#1e2d3d' },
  { key: 'warwick',   zh: '华威',   en: 'University of Warwick',  group: '王爱曼华', mark: '华', color: '#4b1e64' }
];

const DIRS = {
  bio:      { zh: '生物·化学·医药', en: 'Biochem/Chem/Bio/Med', short: '生化医药' },
  physics:  { zh: '物理',           en: 'Physics',               short: '物理' },
  eng:      { zh: '工程',           en: 'Engineering',           short: '工程' },
  econ:     { zh: '经济·管理·金融·会计', en: 'Econ/Management/Finance', short: '经管金融' },
  cs:       { zh: '计算机·数据·AI', en: 'CS/Data/AI',            short: '计算机数据' },
  stats:    { zh: '统计·数学·精算', en: 'Stats/Maths',           short: '统计数学' },
  // 教育 / 人文 / 社科三个方向两个板块都有专业；传媒目前只有香港板块有，某方向在本板块无专业时不显示该筛选项
  edu:      { zh: '教育',           en: 'Education',             short: '教育' },
  arts:     { zh: '人文·语言',      en: 'Arts/Languages',        short: '人文语言' },
  social:   { zh: '社科·法律',      en: 'Social Sciences/Law',   short: '社科法律' },
  media:    { zh: '传媒',           en: 'Communication/Media',   short: '传媒' }
};

// test 取值：''（无笔试）| 'ESAT' | 'TMUA' | 'TARA' | 'LNAT'（法学）| 'STEP'（剑桥数学offer附加）| 'UCAT' | 组合如 'ESAT'+说明写 note
// offer 口径（仅决定表内标签与释义，代码值保持不变）：typical | min | range | college | standard → 显示为 典型 / 最低 / 区间
const PROGRAMS = [

  // ═══════════ 牛津 Oxford（standard：课程页标准要求；均需线上面试） ═══════════
  

  

  { school: 'oxford', dirs: ['bio'], zh: '生物化学（分子与细胞生物学）', en: 'Biochemistry (Molecular and Cellular Biology)',
    degree: 'MBiochem · 4 年', alevel: 'A*AA', ib: '39（HL 化学 7 + 另两门相关 6）', test: '',
    alevelNote: '化学必修 + 另一门科学/数学；A* 须在科学/数学科目', offer: 'standard', note: '无笔试；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biochemistry-molecular-and-cellular' },

  { school: 'oxford', dirs: ['bio'], zh: '生物学', en: 'Biology',
    degree: 'BA / MBiol · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 生物 + 科学/数学之一 7）', test: '',
    alevelNote: '生物必修 + 化学/物理/数学之一；A* 须在科学/数学', offer: 'standard', note: '无笔试；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biology' },

  { school: 'oxford', dirs: ['bio'], zh: '生物医学', en: 'Biomedical Sciences',
    degree: 'MBiomedSci / BA · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766）', test: 'ESAT',
    alevelNote: '生物/化学/物理/数学须选两门；不收 Critical Thinking 等', offer: 'standard', note: 'ESAT：Maths 1 + 自选两门；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/biomedical-sciences' },

  { school: 'oxford', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'MChem · 4 年', alevel: 'A*A*A', ib: '40（HL 化学 7）', test: '',
    alevelNote: '化学 + 数学必修，两个 A* 均须在科学/数学科目', offer: 'standard', note: '无笔试；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/chemistry' },

  { school: 'oxford', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'MPhys / BA · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766，7 在物理或数学）', test: 'ESAT',
    alevelNote: '数学 + 物理必修；A* 须在数学/物理/高数', offer: 'standard', note: '2027 起 ESAT 取代 PAT（Maths1/2 + Physics）；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/physics' },

  { school: 'oxford', dirs: ['eng'], zh: '工程科学', en: 'Engineering Science',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 776，数学与物理均 7）', test: 'ESAT',
    alevelNote: '数学 + 物理必修，两个 A* 在数学/物理/高数', offer: 'standard', note: 'ESAT（Maths1/2 + Physics）；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/engineering-science' },

  { school: 'oxford', dirs: ['econ'], zh: '经济与管理', en: 'Economics and Management',
    degree: 'BA · 3 年', alevel: 'A*AA', ib: '39（HL 766，HL 数学 6 或 7）', test: 'TARA',
    alevelNote: '数学必修（A* 或 A）', offer: 'standard', note: 'TARA 考 Critical Thinking + Problem Solving 两模块',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/economics-and-management' },

  { school: 'oxford', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BA / MCompSci · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766，7 在 HL 数学）', test: 'TMUA',
    alevelNote: '数学 + 高数 A*A（学校开高数须选）；不开高数则 A*AAa 或 A*AA（数学 A*）', offer: 'standard', note: '2027 起 TMUA 取代 MAT；近年约 96% 录取者修过高数',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/computer-science' },

  { school: 'oxford', dirs: ['stats'], zh: '数学（含数学与统计路线）', en: 'Mathematics / Mathematics and Statistics',
    degree: 'BA / MMath · 3 或 4 年', alevel: 'A*A*A', ib: '39（HL 766，7 在 HL 数学）', test: 'TMUA',
    alevelNote: '数学 + 高数均 A*（同 CS 的不开高数替代路径）', offer: 'standard', note: '申请即联合 Math & Stats，第四学期末分纯数 / 数统路线',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/mathematics' },



// ── 牛津 · 社科 / 法律 / 人文（2027 起社科类笔试改考 TARA；法学 LNAT） ──
  { school: 'oxford', dirs: ['social'], zh: '法学（法理学）', en: 'Law (Jurisprudence)',
    degree: 'BA · 3 或 4 年', alevel: 'AAA', ib: '38（HL 666）', test: 'LNAT',
    alevelNote: '无必修科目；作文类科目有帮助', offer: 'standard',
    note: 'LNAT 考试窗口 9 月 1 日–10 月 15 日；无须提交书面作品；须线上面试（12 月）',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/law-jurisprudence' },

  { school: 'oxford', dirs: ['social'], zh: '哲学、政治学与经济学（PPE）', en: 'Philosophy, Politics and Economics',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '39（HL 766）', test: 'TARA',
    alevelNote: '建议修数学至 A-level（非必须，但多数录取者修数学）', offer: 'standard',
    note: 'TARA 三模块（Critical Thinking + Problem Solving + Writing Task）；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/philosophy-politics-and-economics' },

  { school: 'oxford', dirs: ['social'], zh: '心理学（实验心理学）', en: 'Psychology (Experimental)',
    degree: 'BA · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766）', test: 'TARA',
    alevelNote: '强烈建议修一门科学（含心理学）或数学；建议 GCSE 数学 A/7 以上', offer: 'standard',
    note: 'TARA 三模块；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/psychology-experimental' },

  { school: 'oxford', dirs: ['social'], zh: '人类科学', en: 'Human Sciences',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '38（HL 666）', test: 'TARA',
    alevelNote: '无必修；生物或数学有帮助', offer: 'standard',
    note: '跨生物与社会科学的交叉课程；TARA 三模块；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/human-sciences' },

  { school: 'oxford', dirs: ['social'], zh: '地理学', en: 'Geography',
    degree: 'BA · 3 年', alevel: 'A*AA', ib: '39（HL 766）', test: '',
    alevelNote: '建议修地理', offer: 'standard',
    note: '无笔试；无须提交书面作品；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/geography' },

  { school: 'oxford', dirs: ['social', 'arts'], zh: '心理学、哲学与语言学（PPL）', en: 'Psychology, Philosophy and Linguistics',
    degree: 'BA · 3 或 4 年', alevel: 'A*AA', ib: '39（HL 766）', test: 'TARA',
    alevelNote: '建议 GCSE 数学 A/7 以上；心理学方向建议科学/数学，语言学方向建议英语语言、数学、科学或语言',
    offer: 'standard', note: 'TARA 三模块；按 UCAS 代码分心哲 / 心语 / 哲语三条路线；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/psychology-philosophy-and-linguistics' },

  { school: 'oxford', dirs: ['arts'], zh: '历史学', en: 'History',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '38（HL 666）', test: '',
    alevelNote: '强烈建议修历史', offer: 'standard',
    note: '无笔试；须提交一篇 2000 词以内的历史论文；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/history' },

  { school: 'oxford', dirs: ['arts'], zh: '英语语言与文学', en: 'English Language and Literature',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '38（HL 666）', test: '',
    alevelNote: '必修英语文学或英语语言与文学；不接受创意写作资历', offer: 'standard',
    note: '无笔试；须提交一篇英语文学分析文（2000 词以内）；须线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/english-language-and-literature' },

  { school: 'oxford', dirs: ['arts'], qs: [], zh: '古典学（Literae Humaniores）', en: 'Classics',
    degree: 'BA · 4 年', alevel: 'AAA', ib: '39（HL 666）', test: '',
    alevelNote: '无必修；若修拉丁语/希腊语则须达 A；古典文明、古代史或现代语言有帮助', offer: 'standard',
    note: '无笔试；须提交两份书面作品；拉丁 / 希腊语能力在面试中测试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/classics' },

  { school: 'oxford',
    dirs: ['social'],
    zh: '考古与人类学',
    en: 'Archaeology and Anthropology BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '38（HL 666）',
    alevelNote: '无特定科目要求',
    test: '',
    offer: 'standard',
    note: 'UCAS LV64；无入学笔试，需提交两篇近期在校批改论文；12 月线上面试',
    url: 'https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/archaeology-and-anthropology' },



  // ═══════════ 剑桥 Cambridge（Minimum offer level=多数学院标准条件，实际录取普遍更高；offer 由各学院发出） ═══════════
  { school: 'cambridge', dirs: ['bio', 'physics'], zh: '自然科学（生物/化学/物理均在此一门）', en: 'Natural Sciences',
    degree: 'BA (Hons) / MSci · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776）', test: 'ESAT',
    alevelNote: '数学 + 另 2 门科学/数学科目', offer: 'college', note: '申请时须选 Biological 或 Physical 流；实际录取约 76%（生物）/97%（物理）达 A*A*A*',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/natural-sciences-ba-hons-msci' },

  { school: 'cambridge', dirs: ['eng', 'bio'], zh: '化学工程与生物技术', en: 'Chemical Engineering and Biotechnology',
    degree: 'BA (Hons) / MEng · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'ESAT',
    alevelNote: '数学 + 化学 + 第三门科学/数学', offer: 'college', note: 'ESAT',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/chemical-engineering-biotechnology-ba-hons-meng' },

  { school: 'cambridge', dirs: ['eng'], zh: '工程', en: 'Engineering',
    degree: 'BA (Hons) / MEng · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'ESAT',
    alevelNote: '数学 + 物理；学校开高数须至 AS/A；多数学院 A* 落数学/高数', offer: 'college', note: 'Churchill/Selwyn 等学院更高；Peterhouse 申请人可能另加 STEP II grade 2',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/engineering-ba-hons-meng' },

  { school: 'cambridge', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BA (Hons) · 3 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'TMUA',
    alevelNote: '数学为唯一必修；6 所学院另要求高数', offer: 'college', note: '实际约 80% 录取者 A*A*A*',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/economics-ba-hons' },

  { school: 'cambridge', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BA (Hons) / MEng · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'TMUA',
    alevelNote: '数学必修；高数须至 AS/A（学校开设时）；多数学院 A* 在数学/高数', offer: 'college', note: '2027 此课用 TMUA 而非 ESAT；申 Peterhouse/Trinity 另考 CSAT；2025 cycle 约 14 人/位',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/computer-science-ba-hons-meng' },

  { school: 'cambridge', dirs: ['stats'], zh: '数学（含统计路线）', en: 'Mathematics',
    degree: 'BA (Hons) / MMath · 3 或 4 年', alevel: 'A*A*A', ib: '41–42（HL 776，HL 数学 AA）', test: 'STEP',
    alevelNote: '数学 + 高数必修；学院常要求 A* 在数学/高数', offer: 'college', note: 'offer 附加 STEP 2&3 各 grade 1（录取后考）；flexible-offer 学院可 A*A*A*+单 STEP grade 1 替代；申请阶段全体考 TMUA',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/mathematics-ba-hons-mmath' },

  { school: 'cambridge', dirs: ['bio'], zh: '医学', en: 'Medicine',
    degree: 'MB, BChir · 6 年', alevel: 'A*A*A', ib: '41–42（HL 776）', test: 'UCAT',
    alevelNote: '化学必修 + 1 或 2 门科学/数学；多数学院要求化学 A*', offer: 'college', note: '实际多数录取 44+/HL777',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/medicine-mb-bchir' },

  { school: 'cambridge', dirs: ['econ'], zh: '环境、法律与经济（原土地经济）', en: 'Environment, Law, and Economics',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修科目（推荐经济与数学）', offer: 'college', note: '商科直申课程；官方课程名已更新为 Environment, Law and Economics；无考试，部分学院要书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/environment-law-economics-ba-hons' },



// ── 剑桥 · 社科 / 教育 / 人文（仅法学要 LNAT，其余无笔试，改为面试 + 书面作品） ──
  { school: 'cambridge', dirs: ['social'], zh: '法学', en: 'Law',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: 'LNAT',
    alevelNote: '无必修科目', offer: 'college',
    note: 'LNAT；部分学院另要求提交书面作品（Pembroke 需 2 篇）',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/law-ba-hons' },

  { school: 'cambridge', dirs: ['social'], zh: '人文、社会与政治科学（HSPS）', en: 'Human, Social, and Political Sciences',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修；建议英语、历史、古代 / 现代语言', offer: 'college',
    note: '无笔试；须提交 2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/human-social-political-sciences-ba-hons' },

  { school: 'cambridge', dirs: ['social'], zh: '心理与行为科学（PBS）', en: 'Psychological and Behavioural Sciences',
    degree: 'BA (Hons) · 3 年', alevel: 'A*A*A', ib: '41–42（HL 776）', test: '',
    alevelNote: '须至少一门数学/生物/化学/计算机科学/物理；部分学院指定科目', offer: 'college',
    note: '无笔试；部分学院要求 1–2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/psychological-behavioural-sciences-ba-hons' },

  { school: 'cambridge', dirs: ['social'], zh: '地理学', en: 'Geography',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '部分学院要求特定科目（如地理）', offer: 'college',
    note: '无笔试；通常无须提交书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/geography-ba-hons' },

  { school: 'cambridge', dirs: ['edu'], zh: '教育学', en: 'Education',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修；建议英语、历史、语言、社科科目', offer: 'college',
    note: '无笔试；须提交 2 份书面作品；部分学院不招此课',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/education-ba-hons' },

  { school: 'cambridge', dirs: ['arts'], zh: '历史学', en: 'History',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '必修历史', offer: 'college',
    note: '无笔试；须提交 2 份书面作品（Sidney Sussex 为 1 份）',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/history-ba-hons' },

  { school: 'cambridge', dirs: ['arts'], zh: '哲学', en: 'Philosophy',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修；建议数学、宗教研究、哲学、英语、历史、语言', offer: 'college',
    note: '无笔试；Downing 与圣约翰学院须提交 2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/philosophy-ba-hons' },

  { school: 'cambridge', dirs: ['arts'], zh: '英语', en: 'English',
    degree: 'BA (Hons) · 3 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '必修英语文学（或英语语言与文学）', offer: 'college',
    note: '无笔试；须提交 2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/english-ba-hons' },

  { school: 'cambridge', dirs: ['arts'], qs: [], zh: '古典学', en: 'Classics',
    degree: 'BA (Hons) · 3 或 4 年', alevel: 'A*AA', ib: '41–42（HL 776）', test: '',
    alevelNote: '无必修（部分学院有额外科目要求）', offer: 'college',
    note: '无笔试；3 年与 4 年课均须提交 2 份书面作品',
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/classics-ba-hons' },

  { school: 'cambridge',
    dirs: ['social'],
    zh: '考古学',
    en: 'Archaeology BA',
    degree: 'BA · 3 年',
    alevel: 'A*AA',
    ib: '41-42（HL 776）',
    alevelNote: '无特定科目要求',
    test: '',
    offer: 'college',
    note: '覆盖考古、生物人类学、埃及学与亚述学',
    qs: [],
    url: 'https://www.undergraduate.study.cam.ac.uk/courses/archaeology-ba-hons' },


  // ═══════════ 帝国理工 Imperial（/2027/ 版官方页；工程系普遍 ESAT，数学/计算机 TMUA） ═══════════
  { school: 'imperial', dirs: ['bio'], zh: '医学生物科学', en: 'Medical Biosciences',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 生物 6 + 相关科 6）', test: '',
    alevelNote: '生物 A + 化学/数学/高数/物理之一 A', offer: 'min', note: '最低档与典型档相同；无笔试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/medical-biosciences/' },

  { school: 'imperial', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 化学 6 + 相关科）', test: 'ESAT',
    alevelNote: '化学 A + 生物/数学/物理之一 A', offer: 'min', note: '2027 须考 ESAT',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/biochemistry-bsc/' },

  { school: 'imperial', dirs: ['bio'], zh: '生物科学', en: 'Biological Sciences',
    degree: 'BSc / MSci · 3–4 年', alevel: 'AAA', ib: '38（HL 生物 6 + 相关科）', test: 'ESAT',
    alevelNote: '生物 A + 化学/数学/物理之一 A', offer: 'min', note: '2027 起须 ESAT',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/biological-sciences/' },

  { school: 'imperial', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 化学+数学各 6）', test: '',
    alevelNote: '化学 A、数学 A', offer: 'min', note: '典型A*AA；无笔试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/chemistry-bsc/' },

  { school: 'imperial', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '40（HL 数学 7、物理 7）', test: 'ESAT',
    alevelNote: '数学 A*、物理 A*', offer: 'min', note: '典型A*A*A',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/physics-bsc/' },

  { school: 'imperial', dirs: ['eng'], zh: '航空工程', en: 'Aeronautical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学 7、物理 7）', test: 'ESAT',
    alevelNote: '数学 A*、物理 A*（3 科制须 A*）', offer: 'min', note: '典型A*A*A*',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/aeronautical-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '机械工程', en: 'Mechanical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学、物理各 6）', test: 'ESAT',
    alevelNote: '数学 A*；物理 3 科制须 A*', offer: 'min', note: '典型A*A*A*',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/mechanical-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '电子与电气工程', en: 'Electrical and Electronic Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学 7、物理 7）', test: 'ESAT',
    alevelNote: '数学 A*、物理 A*', offer: 'min', note: '典型A*A*A；官方名为 Electrical and Electronic',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/electrical-electronic-engineering-meng/' },

  { school: 'imperial', dirs: ['eng'], zh: '土木工程', en: 'Civil Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学 7、物理 6）', test: 'ESAT',
    alevelNote: '数学 A*、物理 A*', offer: 'min', note: '典型A*A*A/A*AAA',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/civil-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '化学工程', en: 'Chemical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 数学 7、化学 7）', test: 'ESAT',
    alevelNote: '化学 A*、数学 A*', offer: 'min', note: '典型A*A*A',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/chemical-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '设计工程', en: 'Design Engineering',
    degree: 'MEng · 4 年', alevel: 'A*AA', ib: '39（HL 数学 7 + 一科 6）', test: 'ESAT',
    alevelNote: '数学 A* + 两门 AA', offer: 'min', note: '典型A*AA；戴森设计学院',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/design-engineering/' },

  { school: 'imperial', dirs: ['eng'], zh: '生物医学工程', en: 'Biomedical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*AA', ib: '39（HL 数学 6、物理 6）', test: '',
    alevelNote: '数学 A*、物理 A、第三科 A', offer: 'min', note: '页面未列笔试（与其他工程系不同，留意）',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/biomedical-engineering/' },

  { school: 'imperial', dirs: ['econ'], zh: '经济学、金融与数据科学', en: 'Economics, Finance and Data Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 数学 7 + 两门 6）', test: 'TMUA',
    alevelNote: '数学 A*', offer: 'min', note: '商学院本科；TMUA + 线上面试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/economics-finance-data-science/' },

  { school: 'imperial', dirs: ['cs'], zh: '计算机', en: 'Computing',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '41（HL 数学 7 + 相关科 7）', test: 'TMUA',
    alevelNote: '数学 A*', offer: 'min', note: '典型A*A*A；TMUA + 面试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/computing-meng/' },

  { school: 'imperial', dirs: ['cs'], zh: '计算机（三年制）', en: 'Computing',
    degree: 'BEng · 3 年', alevel: 'A*A*A', ib: '41（HL 数学 7 + 相关科 7）', test: 'TMUA',
    alevelNote: '数学 A*', offer: 'min', note: '与 Computing MEng 同系同要求；TMUA + 面试',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/computing-beng/' },

  { school: 'imperial', dirs: ['stats'], zh: '数学', en: 'Mathematics',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 7）', test: 'TMUA',
    alevelNote: '数学 A* + 高数 A*', offer: 'min', note: '典型A*A*A；数学系各方向要求一致',
    url: 'https://www.imperial.ac.uk/study/courses/undergraduate/2027/mathematics-bsc/' },



  // ═══════════ LSE（社科院校，本页收录经管与数学类；多门须 TMUA） ═══════════
  { school: 'lse', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 7）', test: 'TMUA',
    alevelNote: '数学 A* 必修；高数强烈建议', offer: 'typical', note: 'TMUA 必考；高数未修不受损',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics' },

  { school: 'lse', dirs: ['econ'], zh: '计量与数理经济', en: 'Econometrics and Mathematical Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 7）', test: 'TMUA',
    alevelNote: '数学 A*', offer: 'typical', note: 'TMUA 必考',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-econometrics-and-mathematical-economics' },

  { school: 'lse', dirs: ['econ'], zh: '金融学', en: 'Finance',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 7）', test: '',
    alevelNote: '数学 A*', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-finance' },

  { school: 'lse', dirs: ['econ'], zh: '会计与金融', en: 'Accounting and Finance',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 6）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: 'A-level Accounting 可算传统科目但非必需',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-accounting-and-finance' },

  { school: 'lse', dirs: ['econ', 'cs'], zh: '经济学与数据科学', en: 'Economics and Data Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: '2026 新开；TMUA 鼓励；物理/化学等量化科目为良好准备',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics-and-data-science' },

  { school: 'lse', dirs: ['econ'], zh: '管理学', en: 'Management',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766、含数学）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: '偏爱文理混合科目组合',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-management' },

  { school: 'lse', dirs: ['cs'], zh: '数据科学', en: 'Data Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-data-science' },

  { school: 'lse', dirs: ['stats'], zh: '精算科学', en: 'Actuarial Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-actuarial-science' },

  { school: 'lse', dirs: ['stats'], zh: '金融数学与统计', en: 'Financial Mathematics and Statistics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-financial-mathematics-and-statistics' },

  { school: 'lse', dirs: ['stats', 'econ'], zh: '数学与经济', en: 'Mathematics with Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-mathematics-with-economics' },

  { school: 'lse', dirs: ['stats'], zh: '数学、统计与商务', en: 'Mathematics, Statistics and Business',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766、数学 AA 7）', test: 'TMUA',
    alevelNote: '数学 A*；高数若开设须 A', offer: 'typical', note: 'TMUA 鼓励',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-mathematics-statistics-and-business' },



// ── LSE · 社科核心（LSE 本就是社科专门院校；法学 LNAT，其余无笔试、无面试） ──
  { school: 'lse', dirs: ['social'], zh: '法学（法学士）', en: 'LLB Bachelor of Laws',
    degree: 'LLB · 3 年', alevel: 'A*AA', ib: '39（HL 766）', test: 'LNAT',
    alevelNote: '无必修科目；看重阅读写作与论文类科目（历史、英语、经济等）', offer: 'typical',
    note: '所有申请者须考 LNAT',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/llb-bachelor-of-laws' },

  { school: 'lse', dirs: ['social'], zh: '社会学', en: 'BSc Sociology',
    degree: 'BSc · 3 年', alevel: 'AAB', ib: '37（HL 666）', test: '',
    alevelNote: '无必修科目；典型含社会学、心理学、历史、政治、宗教、英语，英语类科目尤其受重视', offer: 'typical',
    note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-sociology' },

  { school: 'lse', dirs: ['social'], zh: '政治学', en: 'BSc Politics',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766）', test: '',
    alevelNote: '无必修科目；典型含政治、历史、英语、经济、社会学、哲学', offer: 'typical',
    note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-politics' },

  { school: 'lse', dirs: ['social'], zh: '政治与经济', en: 'BSc Politics and Economics',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766，含数学）', test: '',
    alevelNote: '数学必修', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-politics-and-economics' },

  { school: 'lse', dirs: ['social'], zh: '国际关系', en: 'BSc International Relations',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766）', test: '',
    alevelNote: '无必修科目；偏好至少两门传统学术科目', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-international-relations' },

  { school: 'lse', dirs: ['social'], zh: '心理与行为科学', en: 'BSc Psychological and Behavioural Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 766，含科学/数学/心理学之一）', test: '',
    alevelNote: '须生物/化学/物理/数学/心理学中至少一门达 A', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-psychological-and-behavioural-science' },

  { school: 'lse', dirs: ['social'], zh: '社会人类学', en: 'BA Social Anthropology',
    degree: 'BA · 3 年', alevel: 'AAB', ib: '37（HL 666）', test: '',
    alevelNote: '无必修科目；偏好文理兼修的广泛选课', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/ba-social-anthropology' },

  { school: 'lse', dirs: ['social'], zh: '地理学', en: 'BA Geography',
    degree: 'BA · 3 年', alevel: 'AAA', ib: '38（HL 766）', test: '',
    alevelNote: '无必修科目；地理与经济为最常见选课', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/ba-geography' },

  { school: 'lse', dirs: ['social'], zh: '经济史', en: 'BSc Economic History',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 766，含经济或历史）', test: '',
    alevelNote: '经济或历史须选其一', offer: 'typical', note: '',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economic-history' },

  { school: 'lse', dirs: ['social', 'arts'], zh: '哲学、政治与经济', en: 'BSc Philosophy, Politics and Economics',
    degree: 'BSc · 4 年', alevel: 'A*AA', ib: '39（HL 766，数学 7）', test: '',
    alevelNote: '数学必修，通常须 A*（或高数 A* + 数学 A）', offer: 'typical',
    note: '四年制，第四年含外部客户实践项目',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-philosophy-politics-and-economics' },

  { school: 'lse',
    dirs: ['social'],
    zh: '国际社会与公共政策',
    en: 'BSc International Social and Public Policy',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '37（HL 666）',
    alevelNote: 'GCSE 英语与数学不低于 B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS L400；社会政策系；contextual A-level BBB / IB 35',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-international-social-and-public-policy' },

  { school: 'lse',
    dirs: ['social'],
    zh: '政治与哲学',
    en: 'BSc Politics and Philosophy',
    degree: 'BSc · 3 年',
    alevel: 'AAA',
    ib: '38（HL 766）',
    alevelNote: 'GCSE 英语与数学不低于 B/6',
    test: '',
    offer: 'typical',
    note: 'UCAS LV25；政府系；contextual A-level AAB / IB 37',
    url: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-politics-and-philosophy' },



  // ═══════════ UCL（新版 /courses/ 课程页；官网有反爬，链接与分数经官网+UCAS 核对） ═══════════
  { school: 'ucl', dirs: ['bio'], zh: '生物医学', en: 'Biomedical Sciences',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 生物+化学各 6）', test: '',
    alevelNote: '生物 + 化学须 AA', offer: 'typical', note: '无笔试；GCSE 英语+数学 B/6',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/biomedical-sciences-bsc' },

  { school: 'ucl', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 18、无低于 5）', test: '',
    alevelNote: '化学必修', offer: 'typical', note: '',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/biochemistry-bsc' },

  { school: 'ucl', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '38（HL 18、化学 6）', test: '',
    alevelNote: '化学 A + 生物/物理/数学之一 A', offer: 'typical', note: 'GCSE 英语 C/4、数学 B/6',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/chemistry-bsc' },

  { school: 'ucl', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7 + 物理 6）', test: '',
    alevelNote: '数学与物理 A*A（不分先后）', offer: 'typical', note: '无额外笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/physics-bsc' },

  { school: 'ucl', dirs: ['eng'], zh: '机械工程', en: 'Mechanical Engineering',
    degree: 'MEng · 4 年（另 3 年 BEng）', alevel: 'A*AA', ib: '39（HL 19、数学+物理 7,6）', test: 'TARA',
    alevelNote: '数学与物理必修，A* 落其一', offer: 'typical', note: '2027 官网列为 TARA（第一轮核验时尚未定稿）',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/mechanical-engineering-meng' },

  { school: 'ucl', dirs: ['eng'], zh: '土木工程', en: 'Civil Engineering',
    degree: 'MEng · 4 年（另 3 年 BEng）', alevel: 'A*AA', ib: '39（HL 19、物理须 SL/HL）', test: '',
    alevelNote: '至少两门 UCL 优先科目，建议数学/物理', offer: 'typical', note: '无笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/civil-engineering-meng' },

  { school: 'ucl', dirs: ['eng'], zh: '电子与电气工程', en: 'Electronic and Electrical Engineering',
    degree: 'BEng · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: 'ESAT',
    alevelNote: '数学 A*；物理或高数优先', offer: 'typical', note: 'IET 认证；ESAT',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/electronic-and-electrical-engineering-beng' },

  { school: 'ucl', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc (Econ) · 3 年', alevel: 'A*AA', ib: '39（HL 数学 7）', test: 'TMUA',
    alevelNote: '数学必修且 A*', offer: 'typical', note: '2027 起须考 TMUA；不收重考',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/economics-bsc-econ' },

  { school: 'ucl', dirs: ['econ'], zh: '管理科学', en: 'Management Science',
    degree: 'BSc · 3 年（另 4 年 MSci）', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: '',
    alevelNote: '数学 A*', offer: 'typical', note: 'GCSE 英语 B/6',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/management-science-bsc' },

  { school: 'ucl', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '40（HL 20、数学 7）', test: 'TARA',
    alevelNote: '数学或高数 A*', offer: 'typical', note: 'CS 系全部本科须考 TARA',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/computer-science-bsc' },

  { school: 'ucl', dirs: ['cs'], zh: '计算机科学（四年制）', en: 'Computer Science',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '40（HL 20、数学 7）', test: 'TARA',
    alevelNote: '“AAA 且数学 A*”或“数学 A + 高数 A*”', offer: 'typical', note: '含 Study Abroad / Year in Industry 变体；TARA',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/computer-science-meng' },

  { school: 'ucl', dirs: ['cs', 'stats'], zh: '数据科学（属统计系）', en: 'Data Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: '',
    alevelNote: 'A* 必须数学；高数偏好', offer: 'typical', note: 'RSS 认证、2023 新设；属统计科学系',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/data-science-bsc' },

  { school: 'ucl', dirs: ['stats'], zh: '统计科学', en: 'Statistics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: '',
    alevelNote: '数学 A*；高数优先', offer: 'typical', note: '无笔试无面试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/statistics-bsc' },

  { school: 'ucl', dirs: ['stats', 'econ'], zh: '统计、经济与金融', en: 'Statistics with Economics and Finance',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '39（HL 19、数学 7）', test: '',
    alevelNote: 'A* 必须数学；高数偏好', offer: 'typical', note: '统计系不收重考；无笔试',
    url: 'https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/statistics-economics-and-finance-bsc' },



  // ═══════════ KCL（成绩在 /requirements 子页） ═══════════
  { school: 'kcl', dirs: ['bio'], zh: '生物医学', en: 'Biomedical Science',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 生物+化学各 6）', test: '',
    alevelNote: '生物与化学各 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/biomedical-science-bsc/entry-requirements' },

  { school: 'kcl', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 生物+化学各 6）', test: '',
    alevelNote: '生物与化学各 A', offer: 'typical', note: '与 Biomedical Science 同档',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/biochemistry-bsc/requirements' },

  { school: 'kcl', dirs: ['bio'], zh: '药学', en: 'Pharmacy',
    degree: 'MPharm · 4 年', alevel: 'AAA', ib: '36（HL 化学 6 + 相关 6）', test: '',
    alevelNote: '化学 A + 生物/数学/物理之一 A；GCSE 英语+数学 6/B', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/pharmacy-mpharm/requirements' },

  { school: 'kcl', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 数学 AA+物理各 6）', test: '',
    alevelNote: '数学与物理各 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/physics-bsc/requirements' },

  { school: 'kcl', dirs: ['eng'], zh: '通用工程', en: 'General Engineering',
    degree: 'BEng · 3 年', alevel: 'AAA', ib: '36（HL 数学 AA 6）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: '同系另有电子/生物医学工程同档',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/general-engineering-beng/entry-requirements' },

  { school: 'kcl', dirs: ['eng'], zh: '电子工程', en: 'Electronic Engineering',
    degree: 'BEng · 3 年', alevel: 'AAA', ib: '36（HL 数学 AA 6）', test: '',
    alevelNote: '数学 A；另需理科实践考核', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/electronic-engineering-beng/requirements' },

  { school: 'kcl', dirs: ['eng'], zh: '生物医学工程', en: 'Biomedical Engineering',
    degree: 'BEng · 3 年', alevel: 'AAA', ib: '36（HL 相关 6）', test: '',
    alevelNote: '数学 A + 生物/化学/CS/高数/物理之一 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/biomedical-engineering-beng/requirements' },

  { school: 'kcl', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 6）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/economics-bsc/requirements' },

  { school: 'kcl', dirs: ['econ'], zh: '经济与管理', en: 'Economics and Management',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 6 + HL 人文/社科 6）', test: '',
    alevelNote: '数学 A + 一门人文/社科 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/economics-and-management-bsc/requirements' },

  { school: 'kcl', dirs: ['econ'], zh: '商业管理', en: 'Business Management',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 人文/社科 6）', test: '',
    alevelNote: '须含一门人文/社科 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/business-management-bsc/entry-requirements' },

  { school: 'kcl', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 6）', test: '',
    alevelNote: '数学或高数 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/computer-science-bsc/requirements' },

  { school: 'kcl', dirs: ['cs'], zh: '人工智能', en: 'Artificial Intelligence',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 6）', test: '',
    alevelNote: '数学或高数 A', offer: 'typical', note: 'Informatics 旗舰',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/artificial-intelligence-bsc/requirements' },

  { school: 'kcl', dirs: ['stats'], zh: '数学与统计', en: 'Mathematics with Statistics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 AA 7）', test: '',
    alevelNote: '数学 A* + 高数 A', offer: 'typical', note: '',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/mathematics-with-statistics-bsc/entry-requirements' },

  { school: 'kcl', dirs: ['stats'], zh: '数学', en: 'Mathematics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 AA 7）', test: '',
    alevelNote: '数学+高数合计 A*A（未学高数可用 AS 高数 A）', offer: 'typical', note: '高数近乎必选',
    url: 'https://www.kcl.ac.uk/study/undergraduate/courses/mathematics-bsc/requirements' },



  // ═══════════ 曼大 Manchester（2027 页；CS 已较 2026 下调） ═══════════
  { school: 'manchester', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAA–AAB', ib: '35（HL 6,6,5）', test: '',
    alevelNote: '含化学；另需生物/物理/数学之一 AB', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00521/bsc-biochemistry/' },

  { school: 'manchester', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '38（HL 7,7,6）', test: '',
    alevelNote: '物理 A* + 数学/高数 A*', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00638/bsc-physics/' },

  { school: 'manchester', dirs: ['eng'], zh: '机械工程', en: 'Mechanical Engineering',
    degree: 'MEng · 4 年', alevel: 'A*A*A', ib: '38（HL 7,7,6）', test: '',
    alevelNote: '数学、物理 + 另 1 门', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03921/meng-mechanical-engineering/' },

  { school: 'manchester', dirs: ['eng'], zh: '电子与电气工程', en: 'Electrical and Electronic Engineering',
    degree: 'MEng · 4 年', alevel: 'A*AA', ib: '37（HL 7,6,6、数学 7）', test: '',
    alevelNote: '数学 A* + 物理/电子/高数/化学/CS 之一 A', offer: 'typical', note: 'BEng 版同存',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03894/meng-electrical-and-electronic-engineering/' },

  { school: 'manchester', dirs: ['eng'], zh: '航空航天工程', en: 'Aerospace Engineering',
    degree: 'MEng · 4 年', alevel: 'A*AA', ib: '37（HL 7,6,6）', test: '',
    alevelNote: '数学+物理+另 1 门（无物理个案可看高数）', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03826/meng-aerospace-engineering/' },

  { school: 'manchester', dirs: ['eng'], zh: '化学工程', en: 'Chemical Engineering',
    degree: 'MEng · 4 年', alevel: 'AAA', ib: '36（HL 6,6,6、数学仅 AA）', test: '',
    alevelNote: '数学 + 化学或物理', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03848/meng-chemical-engineering/' },

  { school: 'manchester', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '数学必修', offer: 'typical', note: 'BAEcon Economics 为 AAA 且数学非强制',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/10224/bsc-economics/' },

  { school: 'manchester', dirs: ['econ'], zh: '会计与金融（BAEcon）', en: 'Accounting and Finance',
    degree: 'BAEcon · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '认可科目至少 1 门（修 2 门优先）', offer: 'typical', note: '商学院旗舰',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/05151/baecon-accounting-and-finance/' },

  { school: 'manchester', dirs: ['econ'], zh: '会计学', en: 'Accounting',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '有优先科目清单（会计/商务/经济/法律/数学等）', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/07808/bsc-accounting/' },

  { school: 'manchester', dirs: ['econ'], zh: '管理学', en: 'Management',
    degree: 'BSc · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/03519/bsc-management/' },

  { school: 'manchester', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '37（HL 7,6,6、数学 AA 7）', test: '',
    alevelNote: '数学 A* + CS/高数/生物/化学/物理之一', offer: 'typical', note: '2027 已从 2026 的 A*A*A/IB38 下调',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00560/bsc-computer-science/' },

  { school: 'manchester', dirs: ['cs', 'econ'], zh: '数据科学与经济学（BAEcon，社科院）', en: 'Data Science and Economics',
    degree: 'BAEcon · 3 年', alevel: 'AAA', ib: '36（HL 6,6,6）', test: '',
    alevelNote: '认可科目 ≥1', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/21873/baecon-data-science-and-economics/' },

  { school: 'manchester', dirs: ['stats'], zh: '数学与统计', en: 'Mathematics and Statistics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '37（HL 7,6,6、数学 7 仅 AA）', test: '',
    alevelNote: '数学或高数 A*', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/07101/bsc-mathematics-and-statistics/' },

  { school: 'manchester', dirs: ['stats'], zh: '数学', en: 'Mathematics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '37（HL 7,6,6、数学 7 仅 AA）', test: '',
    alevelNote: '数学或高数 A*', offer: 'typical', note: '',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00590/bsc-mathematics/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '社会学',
    en: 'BSocSc Sociology',
    degree: 'BSocSc · 3 或 4 年',
    alevel: 'ABB',
    ib: '34（HL 6,5,5）',
    alevelNote: '须含至少一门指定科目（社会学/政治/经济与社会科学史/数学/人类学/哲学/心理/历史/地理等），偏好两门；不接受通识/批判性思维',
    test: '',
    offer: 'typical',
    note: 'UCAS L300；BASS 体系可选 4 年（含海外/实习）',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00678/bsocsc-sociology/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '犯罪学',
    en: 'BA Criminology',
    degree: 'BA · 3 或 4 年',
    alevel: 'AAB（或 ABB + EPQ 达 C）',
    ib: '35（HL 6,6,5）',
    alevelNote: '不接受两门 AS 替代一门 A-level；须含法律/政治/社会学/心理/历史等指定科目之一',
    test: '',
    offer: 'typical',
    note: 'UCAS M901',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/21803/ba-criminology/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '政治与国际关系',
    en: 'BSocSc Politics and International Relations',
    degree: 'BSocSc · 3 或 4 年',
    alevel: 'AAA',
    ib: '36（HL 6,6,6）',
    alevelNote: '须含至少一门指定科目（政府与政治/经济/历史/社会学/哲学/地理等），偏好两门此类科目',
    test: '',
    offer: 'typical',
    note: 'UCAS L200；政治系单荣誉主课',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00675/bsocsc-politics-and-international-relations/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '法律',
    en: 'LLB Law',
    degree: 'LLB · 3 年',
    alevel: 'A*AA',
    ib: '37（HL 7,6,6）',
    alevelNote: '须含至少一门指定科目（法律/经济/历史/政治/哲学/数学等），偏好两门；接受 WJEC 犯罪学应用文凭（须另两门 A-level，含一门 A*）',
    test: '',
    offer: 'typical',
    note: 'UCAS M100；课程页英语项仅列 IELTS，未列 TOEFL/IGCSE-ESL',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/12446/llb-law/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '心理学',
    en: 'BSc Psychology',
    degree: 'BSc · 3 年（4 年含实习/海外）',
    alevel: 'AAA（含指定科目）',
    ib: '36（HL 6,6,6，含指定科目）',
    alevelNote: '须含心理学/生物/人类生物学/化学/物理/统计/数学/进阶数学之一；不接受艺术/设计/音乐/戏剧等表现型科目；数学与进阶数学、生物与人类生物学不可同时计入',
    test: '',
    offer: 'typical',
    note: 'UCAS C800；BPS 认证，毕业可获 Graduate Membership',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00653/bsc-psychology/' },

  { school: 'manchester',
    dirs: ['edu'],
    zh: '教育学',
    en: 'BSc Education',
    degree: 'BSc · 3 年',
    alevel: 'ABB',
    ib: '34（HL 6,5,5）',
    alevelNote: '无指定科目；须提供三门完整 A-level 且同次考试；理科 A-level 须通过实践环节',
    test: '',
    offer: 'typical',
    note: 'UCAS X300；曼大教育学院本科为 BSc Education（无 BA Education），设 Primary/Early Years、International、Special Needs 等方向',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/12384/bsc-education/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '社会人类学',
    en: 'BSocSc Social Anthropology',
    degree: 'BSocSc · 3 或 4 年',
    alevel: 'ABB',
    ib: '34（HL 6,5,5）',
    alevelNote: '须含至少一门指定科目（人类学/社会学/政治/历史/地理/哲学等），偏好两门此类科目',
    test: '',
    offer: 'typical',
    note: 'UCAS L600',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00676/bsocsc-social-anthropology/' },

  { school: 'manchester',
    dirs: ['social'],
    zh: '法律与犯罪学',
    en: 'LLB Law with Criminology',
    degree: 'LLB · 3 年',
    alevel: 'A*AA',
    ib: '37（HL 7,6,6）',
    alevelNote: '须含至少一门指定科目（法律/政治/社会学/心理等）；接受 WJEC 犯罪学三级文凭（须另两门 A-level 含一门 A*）',
    test: '',
    offer: 'typical',
    note: 'UCAS M1M9；面向刑事司法方向',
    url: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/18870/llb-law-with-criminology/' },



  // ═══════════ 爱丁堡 Edinburgh（分数=近年获 offer 区间 from–to；苏格兰一般 4 年；经管为 MA(Hons) 本科） ═══════════
  { school: 'edinburgh', dirs: ['bio'], zh: '生物科学（生化方向）', en: 'Biological Sciences (Biochemistry)',
    degree: 'BSc (Hons) · 4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '生物 B、化学 B，并有一科 A', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/13-biological-sciences-biochemistry' },

  { school: 'edinburgh', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'BSc (Hons) · 3–4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '化学 B + 数学 B', offer: 'range', note: '可直入大二 3 年读完',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/21-chemistry' },

  { school: 'edinburgh', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc (Hons) · 4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '数学 A + 物理 B', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/33-physics' },

  { school: 'edinburgh', dirs: ['eng'], zh: '电子与电气工程', en: 'Electronics and Electrical Engineering',
    degree: 'BEng (Hons) · 3–4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '数学 B + 相关理科 B', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/88-electronics-and-electrical-engineering' },

  { school: 'edinburgh', dirs: ['eng'], zh: '机械工程', en: 'Mechanical Engineering',
    degree: 'BEng (Hons) · 3–4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '数学至少 B + 科学类 B（首选物理）', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/82-mechanical-engineering' },

  { school: 'edinburgh', dirs: ['eng'], zh: '化学工程', en: 'Chemical Engineering',
    degree: 'BEng (Hons) · 3–4 年', alevel: 'AAA–ABB', ib: '37（HL666）–32（HL655）', test: '',
    alevelNote: '数学 B + 化学 B', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/99-chemical-engineering' },

  { school: 'edinburgh', dirs: ['eng'], zh: '土木工程', en: 'Civil Engineering',
    degree: 'BEng (Hons) · 3–4 年', alevel: 'ABB–BBB', ib: '34（HL655）–32（HL555）', test: '',
    alevelNote: '数学 B + 科学类 B', offer: 'range', note: '土木门槛明显低于其他工程',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/76-civil-engineering' },

  { school: 'edinburgh', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'MA (Hons) · 4 年', alevel: 'A*A*A*–A*AA', ib: '40（HL766）–37（HL666）', test: '',
    alevelNote: '数学 B 或 AS 数学 A', offer: 'range', note: '竞争极高，分差上限全 A*；MA=本科荣誉学位',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/122-economics' },

  { school: 'edinburgh', dirs: ['econ'], zh: '会计与金融', en: 'Accounting and Finance',
    degree: 'MA (Hons) · 4 年', alevel: 'A*AA–AAA', ib: '40（HL766）–37（HL666）', test: '',
    alevelNote: '无必修 A-level（GCSE 数学 B/6）', offer: 'range', note: '商学院极热门',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/464-accounting-and-finance' },

  { school: 'edinburgh', dirs: ['econ'], zh: '商业管理', en: 'Business Management',
    degree: 'MA (Hons) · 4 年', alevel: 'A*AA–AAA', ib: '40（HL766）–37（HL666）', test: '',
    alevelNote: 'GCSE 数学 B/6', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/182-business-management' },

  { school: 'edinburgh', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc (Hons) · 4 年', alevel: 'A*A*A*–AAB', ib: '43（HL777）–34（HL665）', test: '',
    alevelNote: '数学 A，须入学前 2 年内取得', offer: 'range', note: '信息学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/57-computer-science' },

  { school: 'edinburgh', dirs: ['stats'], zh: '数学与统计', en: 'Mathematics and Statistics',
    degree: 'BSc (Hons) · 4 年', alevel: 'A*A*A*–A*AB', ib: '38（HL766）–34（HL765）', test: '',
    alevelNote: '数学 A*；建议高数', offer: 'range', note: '',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/63-mathematics-and-statistics' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '社会学',
    en: 'Sociology MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'AAA–AAB',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L300；社会与政治科学学院（School of Social and Political Science）；可选计量方法（Quantitative Methods）方向',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/125-sociology' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '政治学',
    en: 'Politics MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*A*A*–AAA',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L200；社会与政治科学学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/124-politics' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '社会人类学',
    en: 'Social Anthropology MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'AAA–AAB',
    ib: '36（HL665）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L600；社会与政治科学学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/128-social-anthropology' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '国际关系',
    en: 'International Relations MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*A*A*–AAA',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS L250；社会与政治科学学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/377-international-relations' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '法律',
    en: 'Law LLB (Hons)',
    degree: 'LLB (Hons) · 4 年',
    alevel: 'A*A*A–A*AA',
    ib: '40（HL766）–37（HL666）',
    alevelNote: 'A-level 英语（English Literature / English Language / 合并 English）B；GCSE English Language 与 English Literature 均 A/7 可替代 A-level 英语',
    test: '',
    offer: 'range',
    note: 'UCAS M114；爱丁堡法学院（Edinburgh Law School）；4 年制苏格兰法学士（LLB）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/168-law-ordinary-and-honours' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '心理学',
    en: 'Psychology BSc (Hons)',
    degree: 'BSc (Hons) · 4 年',
    alevel: 'A*A*A*–AAA',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '须含生物/化学/计算机/环境科学/地理/地质/数学/物理/心理等指定科目之一 B；GCSE 英语 C/4，GCSE 数学 A/7（或数学+物理 B/6，或数学+双科学 B/6）；IB 补数学 SL 6（若 HL 无数学）',
    test: '',
    offer: 'range',
    note: 'UCAS C802；哲学、心理学与语言科学学院（PPLS）；BPS 认证',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/370-psychology' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '社会政策与社会学',
    en: 'Social Policy and Sociology MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*AA–AAB',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS LL43；社会与政治科学学院',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/141-social-policy-and-sociology' },

  { school: 'edinburgh',
    dirs: ['social'],
    zh: '哲学',
    en: 'Philosophy MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*AA–AAB',
    ib: '36（HL665）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS V500；哲学、心理学与语言科学学院（PPLS）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/311-philosophy' },

  { school: 'edinburgh',
    dirs: ['edu'],
    zh: '体育教育',
    en: 'Physical Education MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语语言 C/4、英语文学 C/4、数学 C/4；IB 补数学 SL 4',
    test: '',
    offer: 'range',
    note: 'UCAS XC61；Moray House 教育与体育学院；每学年含中小学体育教学实习（必修），须加入 Disclosure Scotland PVG 背景审查',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/352-physical-education' },

  { school: 'edinburgh',
    dirs: ['edu'],
    zh: '小学教育（盖尔语方向）',
    en: 'Primary Education with Gaelic (Learners) MA (Hons)',
    degree: 'MA (Hons) · 5 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语语言 C/4、英语文学 C/4、数学 C/4，另需英语以外的一门语言 B/6；IB 补数学 SL 4、外语 SL 5',
    test: '',
    offer: 'range',
    note: 'UCAS 3R67；Moray House 教育与体育学院；5 年制，培养以盖尔语与英语授课的小学教师，含中小学教学实习（必修），须加入 Disclosure Scotland PVG 背景审查',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/629-primary-education-with-gaelic-learners' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '英国文学',
    en: 'English Literature MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*A*A*–A*AA',
    ib: '40（HL766）–37（HL666）',
    alevelNote: 'A-level 英语文学或合并 English B；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS Q306；文学、语言与文化学院（School of Literatures, Languages and Cultures）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/197-english-literature' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '历史学',
    en: 'History MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'A*A*A–AAB',
    ib: '37（HL666）–34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS V100；历史、古典与考古学院（School of History, Classics and Archaeology）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/301-history' },

  { school: 'edinburgh',
    dirs: ['arts'],
    zh: '语言学',
    en: 'Linguistics MA (Hons)',
    degree: 'MA (Hons) · 4 年',
    alevel: 'ABB',
    ib: '34（HL655）',
    alevelNote: '无指定 A-level 科目；GCSE 英语 C/4',
    test: '',
    offer: 'range',
    note: 'UCAS Q100；哲学、心理学与语言科学学院（PPLS）',
    url: 'https://study.ed.ac.uk/programmes/undergraduate/194-linguistics' },



  // ═══════════ 华威 Warwick（2027 官方页） ═══════════
  { school: 'warwick', dirs: ['bio'], zh: '生物医学', en: 'Biomedical Sciences',
    degree: 'BSc · 3 年', alevel: 'AAB / AAA', ib: '34 / 36', test: '',
    alevelNote: 'AAB 含生物+第二门科学；或 AAA 含生物', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-biomedical-sciences/' },

  { school: 'warwick', dirs: ['bio'], zh: '生物化学', en: 'Biochemistry',
    degree: 'BSc · 3 年', alevel: 'AAB / AAA', ib: '34 / 36', test: '',
    alevelNote: 'AAB 含生物+化学；或 AAA 含化学+数学/物理/统计并补生物', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-biochemistry/' },

  { school: 'warwick', dirs: ['bio'], zh: '化学', en: 'Chemistry',
    degree: 'BSc · 3 年', alevel: 'AAB', ib: '34（HL 化学 6 + 第二门理科 5）', test: '',
    alevelNote: '化学 + 数学/高数/物理/生物等之一', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-chemistry/' },

  { school: 'warwick', dirs: ['physics'], zh: '物理', en: 'Physics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 AA 6 + 物理 6）', test: '',
    alevelNote: '数学或高数 + 物理 A', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-physics/' },

  { school: 'warwick', dirs: ['eng'], zh: '工程（通用，大一通识）', en: 'Engineering',
    degree: 'BEng · 3 年', alevel: 'AAA', ib: '36（数学+物理 6,6）', test: '',
    alevelNote: '数学与物理（强 profile 可只含其一）', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/beng-engineering/' },

  { school: 'warwick', dirs: ['econ'], zh: '经济学', en: 'Economics',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 6）', test: '',
    alevelNote: '数学 A', offer: 'typical', note: 'TMUA 高分可降至 AAA',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-economics/' },

  { school: 'warwick', dirs: ['econ'], zh: '会计与金融', en: 'Accounting and Finance',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38（HL 数学 6）', test: '',
    alevelNote: '数学 A；GCSE 英语 6/B', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-accounting-finance/' },

  { school: 'warwick', dirs: ['econ'], zh: '商务与管理', en: 'Business and Management',
    degree: 'BSc · 3 年', alevel: 'A*AA', ib: '38', test: '',
    alevelNote: 'GCSE 数学 7/A + 英语 6/B', offer: 'typical', note: '2026 名 Management，2027 起更名',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-business-management/' },

  { school: 'warwick', dirs: ['econ'], zh: '国际商务与管理（4 年含海外）', en: 'International Business and Management',
    degree: 'BSc · 4 年', alevel: 'A*AA', ib: '38', test: '',
    alevelNote: 'GCSE 数学 7/A + 英语 6/B', offer: 'typical', note: '第三年海外/实习',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-international-business-management/' },

  { school: 'warwick', dirs: ['cs'], zh: '计算机科学', en: 'Computer Science',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 7）', test: '',
    alevelNote: '数学 A*；只取前三门成绩', offer: 'typical', note: '',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-computer-science/' },

  { school: 'warwick', dirs: ['cs', 'stats'], zh: '数据科学（统计系）', en: 'Data Science',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 7）', test: '',
    alevelNote: '数学+高数 A*A，或 A*AA + STEP2/TMUA5.0/AEA；不读高数则 A*A*A*', offer: 'typical', note: '2023 新开热门；可叠加 STEP/TMUA 替代路径',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-data-science/' },

  { school: 'warwick', dirs: ['stats'], zh: 'MORSE（数学-运筹-统计-经济）', en: 'MORSE',
    degree: 'BSc · 3 年', alevel: 'A*A*A', ib: '39（HL 数学 AA 7）', test: '',
    alevelNote: '有高数者：A*A*A 含数学+高数 A*A；无高数者 A*A*A*', offer: 'typical', note: '统计系旗舰；可 +STEP2/TMUA5.0/AEA 替代',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-morse/' },

  { school: 'warwick', dirs: ['stats'], zh: '数学', en: 'Mathematics',
    degree: 'BSc · 3 年', alevel: 'A*A* + A', ib: '39（3HL 数学 AA 6）', test: '',
    alevelNote: '数学+高数均 A*', offer: 'typical', note: '普遍要求 TMUA，未达标 offer 加 STEP grade 2',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-mathematics/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '社会学',
    en: 'Sociology BA',
    degree: 'BA · 3 年',
    alevel: 'ABB',
    ib: '32',
    alevelNote: '无指定 A-level 科目；另需 GCSE English Language 6/B（或 GCSE English Literature 6/B + English Language 4/C）',
    test: '',
    offer: 'typical',
    note: 'UCAS L300；Band B 课程',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-sociology/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '政治学',
    en: 'Politics BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36',
    alevelNote: '无指定 A-level 科目',
    test: '',
    offer: 'typical',
    note: 'UCAS L200；由 PAIS（政治与国际研究系）开设',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-politics/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '政治与国际研究',
    en: 'Politics and International Studies BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36',
    alevelNote: '无指定 A-level 科目',
    test: '',
    offer: 'typical',
    note: 'UCAS L260；华威国际关系方向由 PAIS 系开设（无独立 BA International Relations）',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-politics-international-studies/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '法律',
    en: 'Law LLB',
    degree: 'LLB · 3 年',
    alevel: 'A*AA',
    ib: '38',
    alevelNote: '无指定 A-level 科目；需 GCSE 数学 4/C；多数 GCSE 科目需 7(A)/8-9(A*)；不建议 Law+Sociology+Psychology 三科重合组合',
    test: '',
    offer: 'typical',
    note: 'UCAS M100；不要求 LNAT；Band C 课程',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/llb-law/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '心理学',
    en: 'Psychology BSc',
    degree: 'BSc · 3 年',
    alevel: 'AAB',
    ib: '34',
    alevelNote: 'AAB 须含一门科学（数学/进阶数学/统计/化学/生物/人体生物学/物理）；若不修科学则 AAA/A*AB；需 GCSE 数学/统计 6/B',
    test: '',
    offer: 'typical',
    note: 'BPS 认证；IB 34（含 HL 科学）或 36（无 HL 科学）',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/bsc-psychology/' },

  { school: 'warwick',
    dirs: ['edu'],
    zh: '教育学',
    en: 'Education BA',
    degree: 'BA · 3 年',
    alevel: 'ABB',
    ib: '32',
    alevelNote: '无指定 A-level 科目；另需 GCSE English Language 6/B',
    test: '',
    offer: 'typical',
    note: 'UCAS X35B；华威教育学院（Education Studies）开设',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-education/' },

  { school: 'warwick',
    dirs: ['social'],
    zh: '哲学',
    en: 'Philosophy BA',
    degree: 'BA · 3 年',
    alevel: 'AAA',
    ib: '36',
    alevelNote: '无指定 A-level 科目',
    test: '',
    offer: 'typical',
    note: 'UCAS V500；哲学系开设',
    url: 'https://warwick.ac.uk/study/undergraduate/courses/ba-philosophy/' },

];

// 说明：本数据集只收录各校实际开设的课程，不标注“某校没有某专业”之类的对照信息
